import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_tagline': 'Log your workouts easily, all in one place.',
      'saved_accounts': 'Saved accounts',
      'login': 'Log in',
      'login_with_another': 'Log in using another account',
      'login_as': 'Log in as',
      'new_to_taqa': 'New to TAQA? ',
      'signup': 'Sign up',

      'verification_title': 'Verify Email',
      'verification_sent': 'A verification code has been sent to:',
      'enter_code': 'Enter verification code',
      'hint_code': '6-digit code',
      'verify_btn': 'Verify',
      'resend_btn': 'Resend code',
      'resend_wait': 'Resend available in {seconds} sec',
      'code_invalid': 'Code must be 6 digits',
      'verified_success': 'Email verified successfully!',
      'verification_login_required': 'Please log in to continue.',
      'verified_failed': 'Verification failed',
      'resend_failed': 'Resend failed',
      'resend_success': 'New verification code sent',

      "login_title": "Login",
      "email": "Email",
      "password": "Password",
      "email_hint": "example@gmail.com",
      "password_hint": "Your password",
      "forgot_password": "Forgot Password?",
      "login_btn": "Login",
      "or": "or",
      "apple_login": "Sign in with Apple",
      "google_login": "Sign in with Google",
      "error_required_fields": "Email and password are required",
      "network_error": "Network error",
      "welcome_user": "Welcome, {name}",
      "account_no_longer_exists": "Account no longer exists.",

      "signup_title": "Create Account",
      "signup_username": "Username",
      "signup_username_hint": "yourname_123",
      "signup_fullname": "Full Name",
      "signup_fullname_hint": "First Last",
      "signup_btn": "Create Account",
      "signup_required_fields": "All fields are required.",
      "signup_username_short": "Username must be at least 3 characters.",
      "signup_username_long": "Username cannot exceed 50 characters.",
      "signup_username_invalid": "Username can use letters, numbers, '.', '-' or '_'.",
      "signup_email_invalid": "Enter a valid email.",
      "signup_password_short": "Password must be at least 8 characters.",
      "signup_failed": "Signup failed.",
      "google_signup": "Continue with Google",
      "google_success_message": "Signed in with Google. Welcome!",
      "signup_expert_title": "Create Expert Account",
      "signup_expert_btn": "Create Expert Account",
      "signup_as_expert": "Sign up as expert",
      "signup_expert_note": "Experts manage the platform. Expert accounts may require approval.",

      "questionnaire_title": "Personalized Form",
      "questionnaire_intro_title": "Let’s personalize your plan",
      "questionnaire_intro_text":
          "Answer a few questions so we can adapt your workouts and nutrition to your body, lifestyle, and goals.",
      "questionnaire_chip_time": "Takes ~3–5 min",
      "questionnaire_chip_personal": "Fully personalized",
      "questionnaire_chip_private": "Your data is private",

      "expert_questionnaire_title": "Expert Questionnaire",
      "expert_questionnaire_intro_title": "Tell us about your expertise",
      "expert_questionnaire_intro_text": "A focused 27-question form to understand your background, specialties, and how you can support clients.",
      "expert_questionnaire_chip_count": "27 questions",
      "expert_questionnaire_chip_time": "Takes ~5–8 min",
      "expert_questionnaire_chip_quality": "Helps vet expertise",
      "expert_questionnaire_submit": "Submit expert questionnaire",
      "expert_question_label": "Question",
      "expert_question_hint": "Type your response",
      "expert_section_experience": "Experience",
      "expert_section_experience_sub": "Years coaching, background, education.",
      "expert_section_specialty": "Specialties",
      "expert_section_specialty_sub": "Training styles, nutrition focus, tools.",
      "expert_section_clients": "Clients & availability",
      "expert_section_clients_sub": "Who you serve, capacity, time zones.",
      "expert_placeholder_title": "Expert questionnaire",
      "expert_placeholder_desc": "We’re preparing a tailored 27-question flow. For now, submit to continue.",
      "expert_placeholder_block_title": "Coming soon",
      "expert_placeholder_block_desc": "Detailed expertise questions will appear here.",
      "expert_submission_title": "Application submitted",
      "expert_submission_headline": "Thank you for your expertise",
      "expert_submission_body": "Your expert application was submitted successfully. Please allow 24–48 hours while we review your details.",
      "expert_submission_next_steps": "What happens next",
      "expert_submission_step_review": "We’ll review your answers and verify your expertise.",
      "expert_submission_step_notify": "You’ll receive an email once your application is approved.",
      "expert_submission_step_dashboard": "If approved, you’ll see your expert dashboard unlocked.",
      "expert_questionnaire_already_done": "You already submitted the expert questionnaire.",

      "section_basics_title": "Basics",
      "section_basics_sub": "Age, height, weight, body type.",
      "section_goals_title": "Goals",
      "section_goals_sub": "What you want to achieve & by when.",
      "section_training_title": "Training",
      "section_training_sub": "Experience, days per week, style.",
      "section_nutrition_title": "Nutrition",
      "section_nutrition_sub": "Diet type, allergies, meals.",
      "section_lifestyle_title": "Lifestyle & Health",
      "section_lifestyle_sub": "Sleep, stress, any conditions.",

      "start_questionnaire": "Start questionnaire",
      "update_later": "You can always update your answers later.",
      "save_success": "Questionnaire saved successfully",
      "save_error": "Error saving questionnaire",
      "user_missing": "User ID missing – login again",
      "not_set": "Not set",
      "set_button": "Set",
      "yes": "Yes",
      "no": "No",
      "affiliation": "Affiliation",
      "generating_training_title": "Preparing your training plan",
      "generating_training_body": "Hang tight while we tailor your workouts and nutrition.",
      "generating_training_note": "AI builds your template instantly. An expert will review and verify it within 24–48 hours.",
      "updating_plan_title": "Updating your plan",
      "updating_plan_body": "We’re saving your profile and rebuilding your training and diet.",
      "updating_plan_note": "This can take a moment. Please keep the app open while we update everything.",
      "diet_title": "Diet",
      "diet_daily_targets": "Daily targets",
      "diet_targets_subtitle": "Calories & macros for your plan",
      "diet_offline_targets": "Showing saved targets (offline)",
      "diet_refresh": "Refresh",
      "diet_rest_day": "Rest day",
      "diet_training_day": "Training day",
      "diet_kcal_unit": "kcal",
      "diet_kcal_label": "Kcal",
      "diet_carbs": "Carbs",
      "diet_fat": "Fat",
      "diet_updated": "Updated",
      "diet_today_meals": "Today’s meals",
      "diet_refresh_meals": "Refresh meals",
      "diet_offline_meals": "Showing saved meals (offline)",
      "diet_no_targets_yet": "No diet targets yet.",
      "diet_preparing_plan": "Preparing your diet plan…",
      "diet_no_meals_today": "No meals yet for today.",
      "diet_open_today_meals": "Open today’s meals",
      "diet_meal": "Meal",
      "diet_day": "Day",
      "diet_items_singular": "item",
      "diet_items_plural": "items",
      "diet_add_foods_coming_soon": "Add foods to this meal (coming soon).",
      "diet_more_features_coming": "More diet features are coming soon.",
      "diet_training_day_targets_unavailable": "Training day targets not available yet.",
      "diet_p_short": "P",
      "diet_c_short": "C",
      "diet_f_short": "F",
      "diet_add_item": "Add item",
      "diet_add_item_title": "Add item",
      "diet_add_item_help": "Search and log foods into this meal.",
      "diet_tab_foods": "Foods",
      "diet_tab_restaurants": "Restaurants",
      "diet_search_hint": "Search foods or restaurants…",
      "diet_min_chars": "Type at least 2 characters to search.",
      "diet_no_results": "No results",
      "diet_enter_grams_title": "Enter grams",
      "diet_grams_hint": "e.g. 200",
      "diet_grams_unit": "g",
      "diet_enter_quantity_title": "Enter quantity",
      "diet_quantity_hint": "e.g. 2",
      "diet_quantity_unit": "x",
      "diet_log": "Log",
      "diet_item_added": "Item added",
      "diet_failed_to_add_item": "Failed to add item",
      "diet_remaining_title": "Remaining",
      "diet_remaining": "Remaining",
      "diet_over": "Over by",
      "diet_consumed": "Consumed",
      "diet_freeze_day": "Freeze day",
      "diet_day_already_frozen": "Day frozen",
      "diet_frozen_badge": "Frozen",
      "diet_freeze_note": "Freezing saves a snapshot of today’s targets and remaining.",
      "diet_frozen_note": "Today is frozen. Logging can continue, but the snapshot stays unchanged.",
      "diet_day_frozen": "Day frozen successfully",
      "diet_freeze_failed": "Failed to freeze day",
      "diet_option_search": "Search",
      "diet_option_search_desc": "Search foods and restaurants",
      "diet_option_manual": "Manual Entry",
      "diet_option_manual_desc": "Enter name and macros manually",
      "diet_option_photo": "Photo (AI estimate)",
      "diet_option_photo_desc": "Take or choose a photo and (optionally) add a description",
      "diet_photo_title": "Log from photo",
      "diet_photo_take": "Take photo",
      "diet_photo_pick": "Choose photo",
      "diet_photo_description_optional": "Description (optional)",
      "diet_photo_description_hint": "e.g., Grilled chicken breast with rice",
      "diet_photo_note": "AI will estimate calories and macros from the photo.",
      "diet_photo_too_large": "Photo is too large (max 5MB).",
      "diet_photo_invalid_type": "Unsupported image format. Use JPEG, PNG, HEIC/HEIF, or WebP.",
      "diet_photo_empty": "Photo file is empty. Please pick another photo.",
      "diet_manual_entry_title": "Manual Entry",
      "diet_manual_item_name": "Item Name",
      "diet_manual_item_name_hint": "e.g., Homemade chicken salad",
      "diet_manual_item_name_required": "Item name is required",
      "diet_manual_item_name_too_long": "Item name must be 200 characters or less",
      "diet_manual_calories": "Calories",
      "diet_manual_calories_invalid": "Enter a valid number (≥ 0)",
      "diet_manual_grams": "Grams (optional)",
      "diet_manual_grams_optional": "Optional",
      "diet_manual_grams_invalid": "Enter a valid number (≥ 0)",
      "diet_manual_macros": "Macros",
      "diet_manual_macro_invalid": "Enter a valid number (≥ 0)",
      "diet_manual_prefill_title": "Search foods",
      "diet_manual_prefill_button": "Search foods or ingredients",
      "diet_ingredients_title": "Ingredients",
      "diet_ingredients_empty": "No ingredients added yet.",
      "diet_add_ingredient": "Add ingredient",
      "diet_remove_ingredient": "Remove ingredient",
      "diet_ingredient_search_title": "Search ingredient",
      "diet_manual_search_choice_title": "How do you want to use this?",
      "diet_manual_search_choice_body": "You can use this food as the main logged item or just add it as an ingredient.",
      "diet_manual_search_as_item": "Use as main item",
      "diet_manual_search_as_ingredient": "Add as ingredient",
      "diet_ingredient_name": "Ingredient name",
      "diet_ingredient_name_required": "Ingredient name is required",
      "diet_ingredient_amount": "Amount",
      "diet_ingredient_unit": "Unit",
      "diet_ingredient_optional": "Optional",
      "diet_ingredient_amount_invalid": "Enter a valid amount (> 0)",
      "diet_ingredient_added": "Ingredient added",
      "diet_ingredient_add_failed": "Failed to add ingredient",
      "diet_favorites_title": "Favorite meals",
      "diet_favorites_add_from": "Add from favorites",
      "diet_favorites_save_current": "Save meal as favorite",
      "diet_favorites_save_title": "Save favorite meal",
      "diet_favorites_name": "Meal name",
      "diet_favorites_notes": "Notes (optional)",
      "diet_favorites_name_required": "Meal name is required",
      "diet_favorites_save": "Save favorite",
      "diet_favorites_saved": "Favorite saved",
      "diet_favorites_save_failed": "Failed to save favorite",
      "diet_favorites_empty": "No favorite meals yet.",
      "diet_favorites_empty_meal": "Add at least one item before saving.",
      "diet_favorites_log": "Log favorite",
      "diet_favorites_log_success": "Favorite logged",
      "diet_favorites_log_failed": "Failed to log favorite",
      "diet_favorites_load_failed": "Failed to load favorite",
      "diet_add_meal_title": "Add meal",
      "diet_add_meal_name": "Meal name (optional)",
      "diet_add_meal_name_hint": "e.g., Late snack",
      "diet_add_meal_name_too_long": "Meal name is too long",
      "diet_add_meal_confirm": "Add",
      "diet_add_meal_success": "Meal added",
      "diet_add_meal_failed": "Failed to add meal",
      "diet_delete_meal": "Delete meal",
      "diet_delete_meal_title": "Delete meal",
      "diet_delete_meal_confirm": "Delete",
      "diet_delete_meal_success": "Meal deleted",
      "diet_delete_meal_failed": "Failed to delete meal",
      "diet_delete_meal_confirm_empty": "Delete {meal}?",
      "diet_delete_meal_confirm_has_items": "Delete {meal}? This will remove all items in it.",
      "diet_delete_meal_note": "This deletes the meal and all its items.",
      "diet_delete_item": "Delete item",
      "diet_delete_item_title": "Delete item",
      "diet_delete_item_confirm": "Delete {item}?",
      "diet_delete_item_confirm_button": "Delete",
      "diet_delete_item_success": "Item deleted",
      "diet_delete_item_failed": "Failed to delete item",
      "diet_clear_meal_items": "Clear meal items",
      "diet_clear_meal_title": "Clear meal",
      "diet_clear_meal_confirm": "Remove all items from {meal}?",
      "diet_clear_meal_confirm_button": "Clear",
      "diet_clear_meal_success": "Meal cleared",
      "diet_clear_meal_failed": "Failed to clear meal",

      "sec_basic_title": "Basic Info",
      "sec_goals_title": "Goals & Motivation",
      "sec_training_title": "Training",
      "sec_nutrition_title": "Nutrition",
      "sec_lifestyle_title": "Lifestyle & Recovery",
      "sec_affiliation_title": "Affiliation",
      "sec_affiliation_sub": "Confirm your gym/hospital or add your own.",
      "sec_health_title": "Health & Settings",

      "sec_basic_sub": "Tell us your basic body information.",
      "sec_goals_sub": "What you want to achieve and why.",
      "sec_training_sub": "How you like to train and what you can do.",
      "sec_nutrition_sub": "Your diet habits and preferences.",
      "sec_lifestyle_sub": "Your daily routine, sleep and stress.",
      "sec_health_sub": "Health details and how flexible your plan is.",

      "step": "Step",
      "of": "of",
      "back": "Back",
      "next": "Next",
      "finish": "Finish",
      "common_continue": "Continue",
      "generating_waiting_hint": "This may take a few seconds.",
      "generating_error_title": "Taking longer than usual",
      "generating_error_body": "We couldn't generate your plan yet. You can try again, or continue to the app while we keep working in the background.",
      "generating_retry": "Try again",
      "training_instructions_title": "Instructions",
      "training_start_exercise": "Start Exercise",
      "training_session_title": "Your session",
      "training_log_weight_reps": "Log weight & reps",
      "training_weight_label": "Weight (kg)",
      "training_performed_sets": "Performed Sets",
      "training_performed_reps": "Performed Reps",
      "training_rir_label": "RIR",
      "training_feedback_title": "How was this exercise?",
      "training_feedback_subtitle": "Your feedback helps us tune your next sessions.",
      "training_feedback_submit": "Submit feedback",

      "sex": "Sex",
      "male": "Male",
      "female": "Female",
      "prefer_not": "Prefer not to say",

      "age": "Age",
      "height": "Height",
      "weight": "Weight",

      "goal_main": "What is your main goal?",
      "goal_main_subtitle": "In addition to gaining muscles",
      "lose_weight": "Lose weight",
      "gain_muscle": "Gain muscle",
      "gain_weight": "Gain weight",
      "maintain_weight": "Maintain weight",
      "lose_fat": "Lose fat",
      "build_muscle": "Build muscle",
      "maintain": "Maintain",
      "improve_endurance": "Improve endurance",
      "maintain_fitness": "Maintain fitness",
      "improve_health": "Improve health",

      "motivation": "What motivates you most?",
      "look_better": "Look better",
      "feel_stronger": "Feel stronger",
      "health_better": "Improve health",
      "more_energy": "Increase energy",
      "mental_wellbeing": "Mental well-being",

      "muscle_priority_upper": "Upper body priority",
      "muscle_priority_lower": "Lower body priority",
      "chest": "Chest",
      "shoulders": "Shoulders",
      "back_muscle": "Back",
      "quads": "Quads",
      "hamstrings": "Hamstrings",
      "glutes": "Glutes",

      "time_change": "How soon do you want to see change?",
      "no_timeframe": "No timeframe",

      "deadline": "Do you have a deadline?",
      "sport": "Sporting event",
      "wedding": "Wedding",
      "birthday": "Birthday",
      "vacation": "Vacation",
      "other": "Other",

      "body_type": "Current body type",
      "slender": "Slender",
      "average": "Average",
      "muscular": "Muscular",
      "heavy": "Heavy",

      "fitness_experience": "Fitness experience",
      "beginner": "Beginner (<6 months)",
      "intermediate": "Intermediate (6–24 months)",
      "advanced": "Advanced (>2 years)",

      "training_days": "Training days per week",
      "preferred_time": "Preferred time",
      "morning": "Morning",
      "noon": "Noon",
      "afternoon": "Afternoon",
      "evening": "Evening",
      "flexible": "Flexible",

      "training_location": "Where do you train?",
      "gym": "Gym",
      "home": "Home",
      "hybrid": "Hybrid",

      "training_style": "Preferred training style",
      "strength": "Strength",
      "hypertrophy": "Hypertrophy",
      "functional": "Functional",
      "endurance": "Endurance",
      "hiit": "HIIT",
      "mobility": "Mobility",

      "past_injuries": "Past injuries",
      "shoulder": "Shoulder",
      "knee": "Knee",
      "elbow": "Elbow",
      "none": "None",

      "train_mode": "Train mode",
      "alone": "Alone",
      "partner": "With partner",
      "trainer": "With trainer",

      "auto_recovery": "Include recovery?",

      "diet_type": "Preferred diet",
      "no_pref": "No preference",
      "high_protein": "High protein",
      "low_carb": "Low carb",
      "vegetarian": "Vegetarian",
      "vegan": "Vegan",
      "fasting": "Intermittent fasting",

      "allergies": "Allergies",
      "dairy": "Dairy",
      "gluten": "Gluten",
      "nuts": "Nuts",
      "shellfish": "Shellfish",

      "meals_per_day": "Meals per day",
      "food_habit": "Food habit",
      "cook": "Mostly cook",
      "eat_out": "Mostly eat out",

      "kitchen_access": "Kitchen access",

      "supplements": "Supplements",
      "protein": "Protein",
      "creatine": "Creatine",
      "multivitamin": "Multivitamin",

      "water_intake": "Daily water intake",
      "meal_plan": "Meal plan type",
      "low_budget": "Low budget",
      "moderate": "Moderate",

      "daily_activity": "Daily activity level",
      "sedentary": "Sedentary (desk job)",
      "active": "Active",
      "highly_active": "Highly physical",

      "sleep_hours": "Sleep duration",
      "sleep_consistency": "Sleep consistency",
      "regular": "Regular",
      "irregular": "Irregular",

      "wake_feeling": "Wake feeling",
      "tired": "Tired",
      "okay": "Okay",
      "refreshed": "Refreshed",

      "stress_level": "Stress level",
      "affiliation_heading": "Affiliation",
      "affiliation_category": "Affiliation category",
      "affiliation_select": "Select your institution",
      "affiliation_loading": "Loading affiliations...",
      "affiliation_other": "Other affiliation",
      "affiliation_other_hint": "Type the gym, clinic, or organization name",
      "affiliation_help": "Choose from the list or type it if you don't see it.",
      "affiliation_required": "Please pick an affiliation or type one.",
      "affiliation_none_value": "Not affiliated",
      "affiliation_prompt": "Are you affiliated with a gym/hospital?",
      "affiliation_load_error": "Could not load affiliations. You can still type your own.",

      "chronic_conditions": "Chronic conditions",
      "chronic_prompt": "Do you have chronic diseases?",
      "chronic_none_value": "None",
      "auto_adjust": "Auto-adjust weekly?",
      "consent_tracking": "Consent to tracking?",
      "consent_required": "You must allow tracking to continue.",

      "required": "This field is required",
      "select_option": "Please select an option",
      "select_one": "Please select at least one option",
      "send_reset_code": "Send Reset Code",
"verify_reset_code": "Verify Reset Code",
"reset_code_sent_to": "A reset code was sent to:",
"reset_code_resent": "Reset code resent.",
"enter_reset_code": "Enter the reset code.",
"reset_password": "Reset Password",
"new_password": "New Password",
"retype_password": "Retype Password",
"fill_all_fields": "Please fill all fields.",
"passwords_do_not_match": "Passwords do not match.",
"reset_failed": "Password reset failed.",
"password_reset_success": "Password changed successfully!",
"profile_title": "Profile",
"edit_profile": "Edit Profile",
"sign_out": "Sign Out",
"profile_goals_title": "Goals",
"profile_main_goal": "Main Goal",
      "profile_workout_freq": "Workout Frequency",
      "profile_diet_pref": "Diet Preference",
      "training": "Training",
      "rest_day": "Rest day — recover and come back strong.",
      "no_active_training_program": "No active training program yet.",
      "training_exercise_list_title": "Exercise List",
      "training_exercise_list_sub": "Follow the sets and reps shown for each exercise.",
      "offline_mode": "Offline Mode",
      "offline_mode_using_cached_data": "Offline: Using cached data",
      "exercise_saved_offline": "Exercise saved offline. Will sync when online.",
      "feedback_saved_offline": "Feedback saved offline. Will sync when online.",
      "no_feedback_questions": "No feedback questions available",
      "common_close": "Close",
      "common_confirm": "Confirm",
      "exercise_replace_queued": "Exercise will be replaced when you're back online.",
      "offline_replace_suggestions": "When you're back online, you can get suggestions here.",
      "offline_replace_all_exercises": "When you're back online, you can browse all exercises here.",
      "confirm_replace": "Confirm Replacement",
      "confirm_replace_message": "Are you sure you want to replace \"{old}\" with \"{new}\"?",
      "training_days_change_confirm_title": "Change training days?",
      "training_days_change_confirm_message": "Changing your number of training days per week will regenerate your training program and diet targets. Do you want to continue?",
      "diet_plan_change_confirm_title": "Update your diet plan?",
      "diet_plan_change_confirm_message": "Changing your goal or nutrition will regenerate your diet plan. Your training program will stay the same. Continue?",
      "updating_diet_title": "Updating your diet plan",
      "updating_diet_body": "We’re saving your profile and generating your new diet targets.",
      "updating_diet_note": "Please keep the app open. This may take a moment.",
      "replace_reason_title": "Why are you replacing this exercise?",
      "replace_reason_subtitle": "Please tell us why you're replacing this exercise. This helps us improve your program.",
      "replace_reason_custom": "Or enter your own reason",
      "replace_reason_hint": "e.g., I don't have the equipment",
      "replace_reason_required": "Please provide a reason",
      "replace_reason_no_equipment": "I don't have the equipment",
      "replace_reason_discomfort": "Exercise causes discomfort/pain",
      "replace_reason_preference": "I prefer a different exercise",
      "replace_reason_difficulty": "Exercise is too difficult/easy",
      "replace_reason_other": "Other",
      "start_workout_button": "Start Workout",

      "profile_info_title": "Personal Information",
"profile_age": "Age",
"profile_sex": "Sex",
"profile_height": "Height",
"profile_weight": "Weight",
"profile_user_name": "User Name",
"profile_occupation": "Occupation",
"profile_experience": "Experience",
"profile_days_per_week": "days/week",
"settings": "Settings",
"coming_soon": "Coming soon",
"settings_language": "Language",
"settings_change_password": "Change password",
"settings_change_password_sub": "Reset your password via email",
"settings_security": "Security",
"settings_profile": "Profile",
"settings_change_username": "Change username",
"settings_change_username_sub": "Update your public username",
"username_updated": "Username updated",
"ok": "OK",
"settings_change_avatar": "Change avatar",
"settings_change_avatar_sub": "Pick a new profile picture",
"permissions_required": "Camera or photo access is required to change your avatar.",
"avatar_updated": "Avatar updated",
"settings_be_expert": "Be an expert",
"settings_be_expert_sub": "Start the expert questionnaire",
"settings_delete_account": "Delete account",
"settings_delete_account_sub": "Remove your data, journal, and uploads",
"settings_delete_account_confirm_body": "This will delete your account, journals, metrics, questionnaires, and uploaded documents. This action cannot be undone.",
"settings_delete_account_confirm_yes": "Delete",
"settings_delete_account_success": "Account deleted",
"settings_support": "Support",
"settings_contact": "Contact us",
"settings_contact_sub": "Reach our support team",
"settings_contact_body": "Email us at support@taqa.app and we'll get back to you shortly.",
"settings_help": "Help & FAQ",
"settings_help_sub": "Common questions and answers",
"settings_help_body": "We’re preparing a help center. In the meantime, contact support for any issue.",
"dash_stay_tuned": "Stay tuned",
"dash_announce_here": "Announcements will appear here.",
"dash_news_tag": "News",
"dash_welcome_back": "Welcome back",
"dash_dashboard": "Dashboard",
"common_date": "Date",
"no_entries": "No entries found.",
"dash_hi_name": "Hi, {name}",
"dash_today_steps": "Today's steps",
"dash_today_sleep": "Today's sleep",
"dash_water_intake": "Water intake",
"dash_calories_burned": "Calories burned",
"dash_goal": "Goal",
"dash_unit_l": "L",
"dash_unit_hrs": "hrs",
"dash_unit_kcal": "kcal",
"dash_exercise_progress": "Exercise progress",
"dash_exercise_done_of_total": "{done} of {total} done",
"dash_exercise_unavailable": "No exercise data available",
"dash_loading": "Loading…",
"dash_target": "Target",
"dash_steps_week": "steps / week",
"dash_steps_label": "steps",
"water_title": "Water intake",
"water_goal_label": "Daily goal (L)",
"water_goal_hint": "e.g. 2.5",
"water_intake_label": "Today's intake (L)",
"water_intake_hint": "e.g. 1.8",
"common_cancel": "Cancel",
"common_save": "Save",
"dash_weekly_goal": "Weekly movement goal",
"dash_7day_trends": "7-day trends",
"dash_sleep_hrs": "Sleep (hrs)",
"dash_calories_scaled": "Calories (x100 kcal)",
"dash_no_sleep_data": "No sleep data",
"dash_no_calories_data": "No calories data",
"dash_fueling": "Fueling compliance",
"dash_muscle": "Muscle stimulus",
"dash_taqa_score": "Taqa Score",
"dash_placeholder": "Placeholder",
"journal_title": "Daily Journal",
"journal_placeholder": "Journal placeholder",
"journal_hint": "Tap notifications to land here.",
"date_today": "Today",
"date_yesterday": "Yesterday",
"daily_journal_refresh": "Refresh",
"daily_journal_sign_in_view": "Sign in to view your journal",
"daily_journal_unable_load": "Unable to load",
"daily_journal_login_prompt": "Log in and come back to see your entries.",
"daily_journal_retry": "Please pull to refresh or try again later.",
"daily_journal_no_entry_today": "No entry yet",
"daily_journal_no_entry_date": "No entry on this date",
"daily_journal_prompt_today": "Answer the daily questions to populate your journal.",
"daily_journal_prompt_other": "Use the arrows to view other days.",
"daily_journal_record_today": "Record today",
"daily_journal_sleep_hours_label": "Hours of sleep",
"daily_journal_sleep_hours_hint": "e.g. 7.5",
"daily_journal_sleep_quality_label": "Sleep quality (1–5)",
"daily_journal_caffeine_label": "Caffeine yesterday",
"daily_journal_caffeine_cups": "Cups",
"daily_journal_alcohol_label": "Alcohol yesterday",
"daily_journal_alcohol_drinks": "Drinks",
"daily_journal_hydration_label": "Hydration (liters)",
"daily_journal_hydration_hint": "e.g. 2.5",
"daily_journal_soreness_label": "Experienced soreness or pain",
"daily_journal_stress_label": "Stress level (1–5)",
"daily_journal_mood_label": "Mood upon waking (1–5)",
"daily_journal_sexual_activity_label": "Sexual activity",
"daily_journal_screen_time_label": "Screen time before bed",
"daily_journal_productivity_label": "Productivity and focus during the day (1–5)",
"daily_journal_motivation_label": "Motivation to train (1–5)",
"daily_journal_supplements_label": "Took supplements or medications",
"daily_journal_copy_last": "Same as last time",
"daily_journal_save_entry": "Save entry",
"daily_journal_section_sleep": "Sleep & Recovery",
"daily_journal_section_hydration": "Hydration & Intake",
"daily_journal_section_focus": "Focus & Training",
"daily_journal_sleep_hours_row": "Sleep hours",
"daily_journal_hours_suffix": "h",
"daily_journal_sleep_quality_row": "Sleep quality",
"daily_journal_mood_row": "Mood on waking",
"daily_journal_soreness_row": "Soreness or pain",
"daily_journal_hydration_row": "Hydration",
"daily_journal_caffeine_row": "Caffeine",
"daily_journal_alcohol_row": "Alcohol",
"daily_journal_supplements_row": "Supplements/meds",
"daily_journal_productivity_row": "Productivity/focus",
"daily_journal_motivation_row": "Motivation to train",
"daily_journal_sexual_row": "Sexual activity",
"daily_journal_screen_row": "Screen time before bed",
"daily_journal_entry_for": "Entry for",
"daily_journal_no_entry_for": "No entry for",
"daily_journal_yes": "Yes",
"daily_journal_no": "No",
"daily_journal_cup_single": "cup",
"daily_journal_cup_plural": "cups",
"daily_journal_drink_single": "drink",
"daily_journal_drink_plural": "drinks",
"daily_journal_sign_in_submit": "Please sign in to submit your journal.",
"daily_journal_saved": "Daily journal saved.",
"daily_journal_already_submitted": "Already submitted today.",
"daily_journal_failed_save": "Failed to save: {error}",
"daily_journal_no_previous": "No previous entry to copy.",
"daily_journal_copied": "Copied last entry for today.",
"daily_journal_failed_copy": "Failed to copy: {error}",
"announcements_title": "Announcements",
"latest_news": "Latest news",
"no_announcements": "No announcements yet.",
"steps_title": "Steps",
"steps_edit_today": "Edit today's steps",
"steps_goal_btn": "Goal: {value}",
"sleep_title": "Sleep",
"sleep_edit_today": "Edit today's sleep",
"sleep_goal_btn": "Goal: {value} h",
"calories_title": "Calories burned",
"calories_edit_today": "Edit today's calories",
"calories_goal_btn": "Goal: {value} kcal",
"range_weekly": "Weekly",
"range_monthly": "Monthly",
"range_yearly": "Yearly",
"last_7_days": "Last 7 days",
"range_last7": "Last 7 days",
"range_last30": "Last 30 days",
"range_last_year": "Last year",
"no_steps_range": "No steps data for this range.",
"no_sleep_range": "No sleep data for this range.",
"no_calories_range": "No calorie data for this range.",
"profile_update_success": "Profile updated",
"profile_update_failed": "Profile update failed",
"no_changes": "No changes to save",
"invalid_number": "Enter a valid number",
      "university_student_question": "Are you currently a university student?",
          "select_university": "Select your university",
          "physical_rehab_question": "Are you using TAQA for physical rehabilitation or physiotherapy?",
    },

    'ar': {
      'welcome_tagline': 'سجّل تمارينك بسهولة، في مكان واحد.',
      'saved_accounts': 'الحسابات المحفوظة',
      'login': 'تسجيل الدخول',
      'login_with_another': 'تسجيل الدخول باستخدام حساب آخر',
      'login_as': 'تسجيل الدخول باسم',
      'new_to_taqa': 'هل أنت جديد في TAQA؟ ',
      'signup': 'إنشاء حساب',

      'verification_title': 'تأكيد البريد الإلكتروني',
      'verification_sent': 'تم إرسال رمز التحقق إلى:',
      'enter_code': 'أدخل رمز التحقق',
      'hint_code': 'رمز مكوّن من 6 أرقام',
      'verify_btn': 'تأكيد',
      'resend_btn': 'إعادة إرسال الرمز',
      'resend_wait': 'يمكن إعادة الإرسال خلال {seconds} ثانية',
      'code_invalid': 'الرمز يجب أن يكون 6 أرقام',
      'verified_success': 'تم تأكيد البريد بنجاح!',
      'verification_login_required': 'يرجى تسجيل الدخول للمتابعة.',
      'verified_failed': 'فشل التحقق',
      'resend_failed': 'فشل الإرسال',
      'resend_success': 'تم إرسال رمز جديد',

      "login_title": "تسجيل الدخول",
      "email": "البريد الإلكتروني",
      "password": "كلمة المرور",
      "email_hint": "example@gmail.com",
      "password_hint": "كلمة المرور الخاصة بك",
      "forgot_password": "هل نسيت كلمة المرور؟",
      "login_btn": "تسجيل الدخول",
      "or": "أو",
      "apple_login": "تسجيل الدخول عبر Apple",
      "google_login": "تسجيل الدخول عبر Google",
      "error_required_fields": "البريد الإلكتروني وكلمة المرور مطلوبان",
      "network_error": "خطأ في الشبكة",
      "welcome_user": "مرحباً، {name}",
      "account_no_longer_exists": "الحساب غير موجود.",

      "signup_title": "إنشاء حساب",
      "signup_username": "اسم المستخدم",
      "signup_username_hint": "yourname_123",
      "signup_fullname": "الاسم الكامل",
      "signup_fullname_hint": "الاسم الأول والاسم الأخير",
      "signup_btn": "إنشاء حساب",
      "signup_required_fields": "جميع الحقول مطلوبة.",
      "signup_username_short": "يجب أن يكون اسم المستخدم 3 أحرف على الأقل.",
      "signup_username_long": "لا يمكن أن يتجاوز اسم المستخدم 50 حرفًا.",
      "signup_username_invalid": "يمكن استخدام الحروف والأرقام و '.' و '-' و '_'.",
      "signup_email_invalid": "أدخل بريدًا إلكترونيًا صالحًا.",
      "signup_password_short": "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
      "signup_failed": "فشل في إنشاء الحساب.",
      "google_signup": "المتابعة عبر Google",
      "google_success_message": "تم تسجيل الدخول عبر Google. أهلاً بعودتك!",
      "signup_expert_title": "إنشاء حساب خبير",
      "signup_expert_btn": "إنشاء حساب خبير",
      "signup_as_expert": "التسجيل كخبير",
      "signup_expert_note": "هذا الخيار مخصص لخبراء المنصة. قد يتطلب الحساب موافقة قبل التفعيل.",

      "questionnaire_title": "النموذج الشخصي",
      "questionnaire_intro_title": "لنخصّص خطتك",
      "questionnaire_intro_text":
          "أجب عن بعض الأسئلة لنكي نكيّف التمارين والتغذية حسب جسمك وأسلوب حياتك وأهدافك.",
      "questionnaire_chip_time": "يستغرق ~3–5 دقائق",
      "questionnaire_chip_personal": "مخصّص بالكامل",
      "questionnaire_chip_private": "بياناتك خاصة",

      "expert_questionnaire_title": "نموذج الخبير",
      "expert_questionnaire_intro_title": "حدثنا عن خبرتك",
      "expert_questionnaire_intro_text": "نموذج من 27 سؤالاً لفهم خبرتك، تخصصاتك، وكيفية دعمك للعملاء.",
      "expert_questionnaire_chip_count": "27 سؤالاً",
      "expert_questionnaire_chip_time": "يستغرق ~5–8 دقائق",
      "expert_questionnaire_chip_quality": "يساعدنا على تقييم الخبرة",
      "expert_questionnaire_submit": "إرسال نموذج الخبير",
      "expert_question_label": "السؤال",
      "expert_question_hint": "اكتب إجابتك",
      "expert_section_experience": "الخبرة",
      "expert_section_experience_sub": "سنوات التدريب، الخلفية، التعليم.",
      "expert_section_specialty": "التخصصات",
      "expert_section_specialty_sub": "أنماط التدريب، التركيز الغذائي، الأدوات.",
      "expert_section_clients": "العملاء والتوفر",
      "expert_section_clients_sub": "من تخدم، الطاقة الاستيعابية، المناطق الزمنية.",
      "expert_placeholder_title": "نموذج الخبير",
      "expert_placeholder_desc": "نعمل على تدفق من 27 سؤالاً مخصصاً. يمكنك الإرسال الآن للمتابعة.",
      "expert_placeholder_block_title": "قريباً",
      "expert_placeholder_block_desc": "ستظهر هنا أسئلة تفصيلية عن خبرتك.",
      "expert_submission_title": "تم إرسال طلبك",
      "expert_submission_headline": "شكراً لمشاركتك خبرتك",
      "expert_submission_body": "تم إرسال طلبك كخبير بنجاح. يرجى السماح بـ 24–48 ساعة لمراجعة بياناتك.",
      "expert_submission_next_steps": "ما الذي سيحدث بعد ذلك",
      "expert_submission_step_review": "سنراجع إجاباتك ونُقيّم خبرتك.",
      "expert_submission_step_notify": "ستصلك رسالة بريد إلكتروني عند الموافقة على طلبك.",
      "expert_submission_step_dashboard": "عند الموافقة، ستجد لوحة تحكم الخبير متاحة لك.",
      "expert_questionnaire_already_done": "لقد أكملت استبيان الخبير بالفعل.",

      "section_basics_title": "الأساسيات",
      "section_basics_sub": "العمر، الطول، الوزن، نوع الجسم.",
      "section_goals_title": "الأهداف",
      "section_goals_sub": "ما تريد تحقيقه وبأي وقت.",
      "section_training_title": "التمارين",
      "section_training_sub": "الخبرة، أيام التدريب، الأسلوب.",
      "section_nutrition_title": "التغذية",
      "section_nutrition_sub": "نوع النظام الغذائي، الحساسية، عدد الوجبات.",
      "section_lifestyle_title": "نمط الحياة والصحة",
      "section_lifestyle_sub": "النوم، الضغط، أي حالات صحية.",

      "start_questionnaire": "ابدأ الاستبيان",
      "update_later": "يمكنك تعديل إجاباتك لاحقًا.",
      "save_success": "تم حفظ الاستبيان بنجاح",
      "save_error": "حدث خطأ أثناء الحفظ",
      "user_missing": "لا يوجد رقم مستخدم – يرجى تسجيل الدخول مجددًا",
      "not_set": "غير محدد",
      "set_button": "تعيين",
      "yes": "نعم",
      "no": "لا",
      "affiliation": "الانتساب",
      "generating_training_title": "جارٍ إعداد خطتك التدريبية",
      "generating_training_body": "يرجى الانتظار بينما نخصّص تمارينك وتغذيتك.",
      "generating_training_note": "سيُنشئ الذكاء الاصطناعي القالب فوراً، وسيقوم خبير بمراجعته وتأكيده خلال 24–48 ساعة.",
      "updating_plan_title": "جارٍ تحديث خطتك",
      "updating_plan_body": "نقوم بحفظ ملفك الشخصي وإعادة إنشاء التدريب والتغذية.",
      "updating_plan_note": "قد يستغرق ذلك لحظات. الرجاء إبقاء التطبيق مفتوحًا أثناء التحديث.",
      "diet_title": "التغذية",
      "diet_daily_targets": "الأهداف اليومية",
      "diet_targets_subtitle": "السعرات والمغذّيات لخُطتك",
      "diet_offline_targets": "عرض الأهداف المحفوظة (دون اتصال)",
      "diet_refresh": "تحديث",
      "diet_rest_day": "يوم راحة",
      "diet_training_day": "يوم تدريب",
      "diet_kcal_unit": "kcal",
      "diet_kcal_label": "سعرات",
      "diet_carbs": "كربوهيدرات",
      "diet_fat": "دهون",
      "diet_updated": "آخر تحديث",
      "diet_today_meals": "وجبات اليوم",
      "diet_refresh_meals": "تحديث الوجبات",
      "diet_offline_meals": "عرض الوجبات المحفوظة (دون اتصال)",
      "diet_no_targets_yet": "لا توجد أهداف تغذية بعد.",
      "diet_preparing_plan": "جاري تجهيز خطة التغذية…",
      "diet_no_meals_today": "لا توجد وجبات لليوم بعد.",
      "diet_open_today_meals": "إنشاء وجبات اليوم",
      "diet_meal": "وجبة",
      "diet_day": "يوم",
      "diet_items_singular": "عنصر",
      "diet_items_plural": "عناصر",
      "diet_add_foods_coming_soon": "إضافة الأطعمة لهذه الوجبة (قريباً).",
      "diet_more_features_coming": "ميزات التغذية الأخرى قادمة قريباً.",
      "diet_training_day_targets_unavailable": "أهداف أيام التدريب غير متوفرة بعد.",
      "diet_p_short": "P",
      "diet_c_short": "C",
      "diet_f_short": "F",
      "diet_add_item": "إضافة عنصر",
      "diet_add_item_title": "إضافة عنصر",
      "diet_add_item_help": "ابحث وسجّل الأطعمة داخل هذه الوجبة.",
      "diet_tab_foods": "أطعمة",
      "diet_tab_restaurants": "مطاعم",
      "diet_search_hint": "ابحث عن طعام أو مطعم…",
      "diet_min_chars": "اكتب حرفين على الأقل للبحث.",
      "diet_no_results": "لا توجد نتائج",
      "diet_enter_grams_title": "أدخل الجرامات",
      "diet_grams_hint": "مثال: 200",
      "diet_grams_unit": "جم",
      "diet_enter_quantity_title": "أدخل الكمية",
      "diet_quantity_hint": "مثال: 2",
      "diet_quantity_unit": "x",
      "diet_log": "تسجيل",
      "diet_item_added": "تمت الإضافة",
      "diet_failed_to_add_item": "فشل إضافة العنصر",
      "diet_remaining_title": "المتبقي",
      "diet_remaining": "المتبقي",
      "diet_over": "زيادة",
      "diet_consumed": "المستهلك",
      "diet_freeze_day": "تجميد اليوم",
      "diet_day_already_frozen": "تم تجميد اليوم",
      "diet_frozen_badge": "مجمّد",
      "diet_freeze_note": "التجميد يحفظ لقطة من أهداف اليوم والمتبقي.",
      "diet_frozen_note": "تم تجميد اليوم. يمكنك الاستمرار في التسجيل لكن اللقطة لا تتغير.",
      "diet_day_frozen": "تم تجميد اليوم بنجاح",
      "diet_freeze_failed": "فشل تجميد اليوم",
      "diet_option_search": "البحث",
      "diet_option_search_desc": "البحث عن الأطعمة والمطاعم",
      "diet_option_manual": "إدخال يدوي",
      "diet_option_manual_desc": "أدخل الاسم والماكرو يدوياً",
      "diet_option_photo": "صورة (تقدير بالذكاء الاصطناعي)",
      "diet_option_photo_desc": "التقط أو اختر صورة وأضف وصفاً (اختياري)",
      "diet_photo_title": "تسجيل من صورة",
      "diet_photo_take": "التقاط صورة",
      "diet_photo_pick": "اختيار صورة",
      "diet_photo_description_optional": "وصف (اختياري)",
      "diet_photo_description_hint": "مثال: صدر دجاج مشوي مع أرز",
      "diet_photo_note": "سيقوم الذكاء الاصطناعي بتقدير السعرات والماكرو من الصورة.",
      "diet_photo_too_large": "الصورة كبيرة جداً (الحد الأقصى 5MB).",
      "diet_photo_invalid_type": "صيغة الصورة غير مدعومة. استخدم JPEG أو PNG أو HEIC/HEIF أو WebP.",
      "diet_photo_empty": "ملف الصورة فارغ. يرجى اختيار صورة أخرى.",
      "diet_manual_entry_title": "إدخال يدوي",
      "diet_manual_item_name": "اسم العنصر",
      "diet_manual_item_name_hint": "مثال: سلطة دجاج منزلية",
      "diet_manual_item_name_required": "اسم العنصر مطلوب",
      "diet_manual_item_name_too_long": "يجب أن يكون اسم العنصر 200 حرف أو أقل",
      "diet_manual_calories": "السعرات الحرارية",
      "diet_manual_calories_invalid": "أدخل رقماً صحيحاً (≥ 0)",
      "diet_manual_grams": "الجرامات (اختياري)",
      "diet_manual_grams_optional": "اختياري",
      "diet_manual_grams_invalid": "أدخل رقماً صحيحاً (≥ 0)",
      "diet_manual_macros": "الماكرو",
      "diet_manual_macro_invalid": "أدخل رقماً صحيحاً (≥ 0)",
      "diet_manual_prefill_title": "بحث عن أطعمة",
      "diet_manual_prefill_button": "ابحث عن أطعمة أو مكونات",
      "diet_ingredients_title": "المكونات",
      "diet_ingredients_empty": "لم يتم إضافة مكونات بعد.",
      "diet_add_ingredient": "إضافة مكوّن",
      "diet_remove_ingredient": "إزالة مكوّن",
      "diet_ingredient_search_title": "ابحث عن مكوّن",
      "diet_manual_search_choice_title": "كيف تريد استخدام هذا الطعام؟",
      "diet_manual_search_choice_body": "يمكنك استخدام هذا الطعام كعنصر الوجبة الرئيسي أو إضافته كمكوّن فقط.",
      "diet_manual_search_as_item": "استخدام كعنصر رئيسي",
      "diet_manual_search_as_ingredient": "إضافة كمكوّن",
      "diet_ingredient_name": "اسم المكوّن",
      "diet_ingredient_name_required": "اسم المكوّن مطلوب",
      "diet_ingredient_amount": "الكمية",
      "diet_ingredient_unit": "الوحدة",
      "diet_ingredient_optional": "اختياري",
      "diet_ingredient_amount_invalid": "أدخل كمية صحيحة (> 0)",
      "diet_ingredient_added": "تمت إضافة المكوّن",
      "diet_ingredient_add_failed": "فشل إضافة المكوّن",
      "diet_favorites_title": "الوجبات المفضلة",
      "diet_favorites_add_from": "إضافة من المفضلة",
      "diet_favorites_save_current": "حفظ الوجبة كمفضلة",
      "diet_favorites_save_title": "حفظ وجبة مفضلة",
      "diet_favorites_name": "اسم الوجبة",
      "diet_favorites_notes": "ملاحظات (اختياري)",
      "diet_favorites_name_required": "اسم الوجبة مطلوب",
      "diet_favorites_save": "حفظ المفضلة",
      "diet_favorites_saved": "تم حفظ المفضلة",
      "diet_favorites_save_failed": "فشل حفظ المفضلة",
      "diet_favorites_empty": "لا توجد وجبات مفضلة بعد.",
      "diet_favorites_empty_meal": "أضف عنصرًا واحدًا على الأقل قبل الحفظ.",
      "diet_favorites_log": "تسجيل المفضلة",
      "diet_favorites_log_success": "تم تسجيل المفضلة",
      "diet_favorites_log_failed": "فشل تسجيل المفضلة",
      "diet_favorites_load_failed": "فشل تحميل المفضلة",
      "diet_add_meal_title": "إضافة وجبة",
      "diet_add_meal_name": "اسم الوجبة (اختياري)",
      "diet_add_meal_name_hint": "مثال: سناك متأخر",
      "diet_add_meal_name_too_long": "اسم الوجبة طويل جداً",
      "diet_add_meal_confirm": "إضافة",
      "diet_add_meal_success": "تمت إضافة الوجبة",
      "diet_add_meal_failed": "فشل إضافة الوجبة",
      "diet_delete_meal": "حذف الوجبة",
      "diet_delete_meal_title": "حذف الوجبة",
      "diet_delete_meal_confirm": "حذف",
      "diet_delete_meal_success": "تم حذف الوجبة",
      "diet_delete_meal_failed": "فشل حذف الوجبة",
      "diet_delete_meal_confirm_empty": "هل تريد حذف {meal}؟",
      "diet_delete_meal_confirm_has_items": "هل تريد حذف {meal}؟ سيتم حذف كل العناصر بداخلها.",
      "diet_delete_meal_note": "سيتم حذف الوجبة وكل عناصرها.",
      "diet_delete_item": "حذف العنصر",
      "diet_delete_item_title": "حذف العنصر",
      "diet_delete_item_confirm": "هل تريد حذف {item}؟",
      "diet_delete_item_confirm_button": "حذف",
      "diet_delete_item_success": "تم حذف العنصر",
      "diet_delete_item_failed": "فشل حذف العنصر",
      "diet_clear_meal_items": "تفريغ عناصر الوجبة",
      "diet_clear_meal_title": "تفريغ الوجبة",
      "diet_clear_meal_confirm": "هل تريد حذف كل العناصر من {meal}؟",
      "diet_clear_meal_confirm_button": "تفريغ",
      "diet_clear_meal_success": "تم تفريغ الوجبة",
      "diet_clear_meal_failed": "فشل تفريغ الوجبة",

      "sec_basic_title": "المعلومات الأساسية",
      "sec_goals_title": "الأهداف والدوافع",
      "sec_training_title": "التمارين",
      "sec_nutrition_title": "التغذية",
      "sec_lifestyle_title": "نمط الحياة والاستشفاء",
      "sec_affiliation_title": "جهة الانتساب",
      "sec_affiliation_sub": "أكد جهة الانتساب أو اكتبها إذا لم تجدها.",
      "sec_health_title": "الصحة والإعدادات",

      "sec_basic_sub": "أدخل معلوماتك الجسدية الأساسية.",
      "sec_goals_sub": "ما الذي تريد تحقيقه ولماذا.",
      "sec_training_sub": "أسلوب تدريبك وقدراتك.",
      "sec_nutrition_sub": "عاداتك الغذائية وتفضيلاتك.",
      "sec_lifestyle_sub": "روتينك اليومي، النوم والضغط.",
      "sec_health_sub": "تفاصيل صحية ومدى مرونة برنامجك.",

      "step": "الخطوة",
      "of": "من",
      "back": "رجوع",
      "next": "التالي",
      "finish": "إنهاء",
      "common_continue": "متابعة",
      "generating_waiting_hint": "قد يستغرق الأمر بضع ثوانٍ.",
      "generating_error_title": "الأمر يستغرق وقتاً أطول من المعتاد",
      "generating_error_body": "لم نتمكن من إنشاء خطتك بعد. يمكنك المحاولة مرة أخرى أو المتابعة إلى التطبيق بينما نتابع العمل في الخلفية.",
      "generating_retry": "إعادة المحاولة",
      "training_instructions_title": "التعليمات",
      "training_start_exercise": "ابدأ التمرين",
      "training_session_title": "جلستك",
      "training_log_weight_reps": "سجل الوزن والتكرارات",
      "training_weight_label": "الوزن (كجم)",
      "training_performed_sets": "المجموعات المنفذة",
      "training_performed_reps": "التكرارات المنفذة",
      "training_rir_label": "RIR",
      "training_feedback_title": "كيف كان هذا التمرين؟",
      "training_feedback_subtitle": "ملاحظاتك تساعدنا على تحسين الجلسات القادمة.",
      "training_feedback_submit": "إرسال التقييم",

      "sex": "الجنس",
      "male": "ذكر",
      "female": "أنثى",
      "prefer_not": "أفضل عدم القول",

      "age": "العمر",
      "height": "الطول",
      "weight": "الوزن",

      "goal_main": "ما هو هدفك الأساسي؟",
      "goal_main_subtitle": "بالإضافة إلى زيادة العضلات",
      "lose_weight": "خسارة الوزن",
      "gain_muscle": "زيادة العضلات",
      "gain_weight": "زيادة الوزن",
      "maintain_weight": "الحفاظ على الوزن",
      "lose_fat": "خسارة الدهون",
      "build_muscle": "بناء العضلات",
      "maintain": "الحفاظ",
      "improve_endurance": "تحسين التحمل",
      "maintain_fitness": "الحفاظ على اللياقة",
      "improve_health": "تحسين الصحة",

      "motivation": "ما الذي يحفّزك أكثر؟",
      "look_better": "المظهر الأفضل",
      "feel_stronger": "الشعور بالقوة",
      "health_better": "تحسين الصحة",
      "more_energy": "طاقة أكبر",
      "mental_wellbeing": "الصحة النفسية",

      "muscle_priority_upper": "أولوية الجزء العلوي",
      "muscle_priority_lower": "أولوية الجزء السفلي",
      "chest": "الصدر",
      "shoulders": "الأكتاف",
      "back_muscle": "الظهر",
      "quads": "الأفخاذ الأمامية",
      "hamstrings": "أوتار الركبة",
      "glutes": "الألوية",

      "time_change": "متى تريد رؤية التغيير؟",
      "no_timeframe": "بدون إطار زمني",

      "deadline": "هل لديك موعد نهائي؟",
      "sport": "حدث رياضي",
      "wedding": "زفاف",
      "birthday": "عيد ميلاد",
      "vacation": "إجازة",
      "other": "أخرى",

      "body_type": "نوع الجسم",
      "slender": "نحيف",
      "average": "متوسط",
      "muscular": "عضلي",
      "heavy": "ثقيل",

      "fitness_experience": "الخبرة الرياضية",
      "beginner": "مبتدئ (<6 أشهر)",
      "intermediate": "متوسط (6–24 شهرًا)",
      "advanced": "متقدم (>سنتين)",

      "training_days": "أيام التمرين أسبوعيًا",
      "preferred_time": "الوقت المفضل",
      "morning": "الصباح",
      "noon": "الظهيرة",
      "afternoon": "بعد الظهر",
      "evening": "المساء",
      "flexible": "مرن",

      "training_location": "مكان التدريب",
      "gym": "نادي رياضي",
      "home": "المنزل",
      "hybrid": "كلاهما",

      "training_style": "أسلوب التدريب",
      "strength": "قوة",
      "hypertrophy": "تضخيم",
      "functional": "وظيفي",
      "endurance": "تحمل",
      "hiit": "HIIT",
      "mobility": "مرونة",

      "past_injuries": "الإصابات السابقة",
      "shoulder": "الكتف",
      "knee": "الركبة",
      "elbow": "الكوع",
      "none": "لا يوجد",

      "train_mode": "طريقة التدريب",
      "alone": "بمفردي",
      "partner": "مع شريك",
      "trainer": "مع مدرب",

      "auto_recovery": "تضمين الاستشفاء؟",

      "diet_type": "النظام الغذائي",
      "no_pref": "بدون تفضيل",
      "high_protein": "عالي البروتين",
      "low_carb": "منخفض الكربوهيدرات",
      "vegetarian": "نباتي",
      "vegan": "نباتي صارم",
      "fasting": "صيام متقطع",

      "allergies": "الحساسية",
      "dairy": "منتجات الألبان",
      "gluten": "الجلوتين",
      "nuts": "المكسرات",
      "shellfish": "المأكولات البحرية",

      "meals_per_day": "عدد الوجبات يوميًا",
      "food_habit": "عادات الطعام",
      "cook": "أطبخ غالبًا",
      "eat_out": "آكل خارج المنزل غالبًا",

      "kitchen_access": "إمكانية استخدام المطبخ",

      "supplements": "المكملات الغذائية",
      "protein": "بروتين",
      "creatine": "كرياتين",
      "multivitamin": "فيتامينات متعددة",

      "water_intake": "كمية الماء اليومية",
      "meal_plan": "نوع خطة الوجبات",
      "low_budget": "ميزانية منخفضة",
      "moderate": "متوسطة",

      "daily_activity": "مستوى النشاط اليومي",
      "sedentary": "خامل (عمل مكتبي)",
      "active": "نشط",
      "highly_active": "نشط جدًا",

      "sleep_hours": "مدة النوم",
      "sleep_consistency": "انتظام النوم",
      "regular": "منتظم",
      "irregular": "غير منتظم",

      "wake_feeling": "الشعور عند الاستيقاظ",
      "tired": "متعب",
      "okay": "عادي",
      "refreshed": "منتعش",

      "stress_level": "مستوى التوتر",
      "affiliation_heading": "جهة الانتساب",
      "affiliation_category": "فئة الجهة",
      "affiliation_select": "اختر الجهة",
      "affiliation_loading": "جارٍ تحميل الجهات...",
      "affiliation_other": "جهة أخرى",
      "affiliation_other_hint": "اكتب اسم النادي أو العيادة أو الجهة",
      "affiliation_help": "اختر من القائمة أو اكتبها إذا لم تجدها.",
      "affiliation_required": "يرجى اختيار جهة أو كتابتها.",
      "affiliation_none_value": "بدون جهة",
      "affiliation_prompt": "هل أنت منتسب لنادٍ أو مستشفى؟",
      "affiliation_load_error": "تعذّر تحميل الجهات، يمكنك كتابة الجهة يدويًا.",

      "chronic_conditions": "الحالات المزمنة",
      "chronic_prompt": "هل لديك أمراض مزمنة؟",
      "chronic_none_value": "لا يوجد",
      "auto_adjust": "تعديل تلقائي أسبوعيًا؟",
      "consent_tracking": "السماح بالتتبع؟",
      "consent_required": "يجب السماح بالتتبع للمتابعة.",

      "required": "هذا الحقل مطلوب",
      "select_option": "الرجاء اختيار خيار",
      "select_one": "الرجاء اختيار خيار واحد على الأقل",
      "send_reset_code": "إرسال رمز الإستعادة",
      "verify_reset_code": "تأكيد رمز الاستعادة",
"reset_code_sent_to": "تم إرسال رمز الاستعادة إلى:",
"reset_code_resent": "تم إعادة إرسال رمز الاستعادة.",
"enter_reset_code": "أدخل رمز الاستعادة.",
"reset_password": "إعادة تعيين كلمة المرور",
"new_password": "كلمة المرور الجديدة",
"retype_password": "أعد إدخال كلمة المرور",
"fill_all_fields": "يرجى تعبئة جميع الحقول.",
"passwords_do_not_match": "كلمتا المرور غير متطابقتين.",
"reset_failed": "فشل في إعادة تعيين كلمة المرور.",
"password_reset_success": "تم تغيير كلمة المرور بنجاح!",
"profile_title": "الملف الشخصي",
"edit_profile": "تعديل الملف",
"sign_out": "تسجيل الخروج",
"profile_goals_title": "الأهداف",
"profile_main_goal": "الهدف الرئيسي",
"profile_workout_freq": "معدل التمرين الأسبوعي",
"profile_diet_pref": "النظام الغذائي",
"training": "التدريب",
"rest_day": "يوم راحة — استشفِ وعد بقوة.",
"no_active_training_program": "لا يوجد برنامج تدريبي مفعل حتى الآن.",
"training_exercise_list_title": "قائمة التمارين",
"training_exercise_list_sub": "اتبع عدد المجموعات والتكرارات لكل تمرين كما هو موضح.",
"offline_mode": "وضع عدم الاتصال",
"offline_mode_using_cached_data": "عدم الاتصال: استخدام البيانات المخزنة",
"exercise_saved_offline": "تم حفظ التمرين في وضع عدم الاتصال. سيتم المزامنة عند الاتصال.",
"feedback_saved_offline": "تم حفظ الملاحظات في وضع عدم الاتصال. سيتم المزامنة عند الاتصال.",
"no_feedback_questions": "لا توجد أسئلة ملاحظات متاحة",
"common_close": "إغلاق",
"common_confirm": "تأكيد",
"exercise_replace_queued": "سيتم استبدال التمرين عند عودة الاتصال بالإنترنت.",
"offline_replace_suggestions": "عند عودة الاتصال بالإنترنت، يمكنك الحصول على الاقتراحات هنا.",
"offline_replace_all_exercises": "عند عودة الاتصال بالإنترنت، يمكنك تصفح جميع التمارين هنا.",
"confirm_replace": "تأكيد الاستبدال",
"confirm_replace_message": "هل أنت متأكد من استبدال \"{old}\" بـ \"{new}\"؟",
"training_days_change_confirm_title": "تغيير أيام التمرين؟",
"training_days_change_confirm_message": "تغيير عدد أيام التمرين أسبوعياً سيُعيد إنشاء برنامج التدريب وأهداف التغذية. هل تريد المتابعة؟",
"diet_plan_change_confirm_title": "تحديث خطة التغذية؟",
"diet_plan_change_confirm_message": "تغيير هدفك أو التغذية سيُعيد إنشاء خطة التغذية. برنامج التدريب سيبقى كما هو. متابعة؟",
"updating_diet_title": "جارٍ تحديث خطة التغذية",
"updating_diet_body": "نحفظ ملفك الشخصي وننشئ أهداف التغذية الجديدة.",
"updating_diet_note": "يرجى إبقاء التطبيق مفتوحاً. قد يستغرق ذلك لحظة.",
"replace_reason_title": "لماذا تقوم باستبدال هذا التمرين؟",
"replace_reason_subtitle": "يرجى إخبارنا لماذا تقوم باستبدال هذا التمرين. هذا يساعدنا على تحسين برنامجك.",
"replace_reason_custom": "أو أدخل السبب الخاص بك",
"replace_reason_hint": "مثال: ليس لدي المعدات",
"replace_reason_required": "يرجى تقديم سبب",
"replace_reason_no_equipment": "ليس لدي المعدات",
"replace_reason_discomfort": "التمرين يسبب عدم الراحة/الألم",
"replace_reason_preference": "أفضل تمرين مختلف",
"replace_reason_difficulty": "التمرين صعب جداً/سهل جداً",
"replace_reason_other": "أخرى",
"start_workout_button": "ابدأ التمرين",
"profile_info_title": "المعلومات الشخصية",
"profile_age": "العمر",
"profile_sex": "الجنس",
"profile_height": "الطول",
"profile_weight": "الوزن",
"profile_occupation": "الوظيفة",
"profile_user_name": "اسم المستخدم",
"profile_experience": "الخبرة",
"profile_days_per_week": "أيام/أسبوع",
"settings": "الإعدادات",
"coming_soon": "قريباً",
"settings_language": "اللغة",
"settings_change_password": "تغيير كلمة المرور",
"settings_change_password_sub": "أعد تعيين كلمة المرور عبر البريد الإلكتروني",
"settings_security": "الأمان",
"settings_profile": "الملف الشخصي",
"settings_change_username": "تغيير اسم المستخدم",
"settings_change_username_sub": "تحديث اسمك العام",
"username_updated": "تم تحديث اسم المستخدم",
"ok": "حسناً",
"settings_change_avatar": "تغيير الصورة الشخصية",
"settings_change_avatar_sub": "اختر صورة جديدة للملف الشخصي",
"permissions_required": "مطلوب إذن الكاميرا أو الصور لتغيير صورتك الشخصية.",
"avatar_updated": "تم تحديث الصورة الشخصية",
"settings_be_expert": "كن خبيراً",
"settings_be_expert_sub": "ابدأ استبيان الخبير",
"settings_delete_account": "حذف الحساب",
"settings_delete_account_sub": "حذف بياناتك ومذكراتك وتحميلاتك",
"settings_delete_account_confirm_body": "سيتم حذف حسابك وكل المذكرات والقياسات والاستبيانات والوثائق المرفوعة. هذا الإجراء لا يمكن التراجع عنه.",
"settings_delete_account_confirm_yes": "حذف",
"settings_delete_account_success": "تم حذف الحساب",
"settings_support": "الدعم",
"settings_contact": "اتصل بنا",
"settings_contact_sub": "تواصل مع فريق الدعم",
"settings_contact_body": "راسلنا على support@taqa.app وسنعاود الاتصال بك في أقرب وقت.",
"settings_help": "المساعدة والأسئلة الشائعة",
"settings_help_sub": "أبرز الأسئلة والإجابات",
"settings_help_body": "نجهّز مركز مساعدة. يمكنك التواصل مع الدعم لأي استفسار.",
"dash_stay_tuned": "ابقَ على اطلاع",
"dash_announce_here": "ستظهر الإعلانات هنا.",
"dash_news_tag": "أخبار",
"dash_welcome_back": "مرحباً بعودتك",
"dash_dashboard": "لوحة التحكم",
"common_date": "التاريخ",
"no_entries": "لا توجد سجلات.",
"dash_hi_name": "مرحباً، {name}",
"dash_today_steps": "خطوات اليوم",
"dash_today_sleep": "نوم اليوم",
"dash_water_intake": "شرب الماء",
"dash_calories_burned": "السعرات المحروقة",
"dash_goal": "الهدف",
"dash_unit_l": "لتر",
"dash_unit_hrs": "س",
"dash_unit_kcal": "سعرة",
"dash_exercise_progress": "تقدّم التمارين",
"dash_exercise_done_of_total": "{done} من {total} مكتملة",
"dash_exercise_unavailable": "لا توجد بيانات تمارين",
"dash_loading": "جارٍ التحميل…",
"dash_target": "الهدف",
"dash_steps_week": "خطوة / أسبوع",
"dash_steps_label": "خطوة",
"water_title": "شرب الماء",
"water_goal_label": "الهدف اليومي (لتر)",
"water_goal_hint": "مثال 2.5",
"water_intake_label": "كمية اليوم (لتر)",
"water_intake_hint": "مثال 1.8",
"common_cancel": "إلغاء",
"common_save": "حفظ",
"dash_weekly_goal": "هدف الحركة الأسبوعي",
"dash_7day_trends": "اتجاهات 7 أيام",
"dash_sleep_hrs": "النوم (س)",
"dash_calories_scaled": "السعرات (x100)",
"dash_no_sleep_data": "لا توجد بيانات نوم",
"dash_no_calories_data": "لا توجد بيانات سعرات",
"dash_fueling": "الالتزام بالتغذية",
"dash_muscle": "تحفيز العضلات",
"dash_taqa_score": "درجة طاقة",
"dash_placeholder": "قريباً",
"journal_title": "المفكرة اليومية",
"journal_placeholder": "صفحة المفكرة",
"journal_hint": "اضغط على الإشعارات للوصول هنا.",
"date_today": "اليوم",
"date_yesterday": "أمس",
"daily_journal_refresh": "تحديث",
"daily_journal_sign_in_view": "سجّل الدخول لعرض المفكرة",
"daily_journal_unable_load": "تعذر التحميل",
"daily_journal_login_prompt": "سجّل الدخول للعودة ورؤية المدخلات.",
"daily_journal_retry": "اسحب للتحديث أو حاول لاحقاً.",
"daily_journal_no_entry_today": "لا يوجد إدخال بعد",
"daily_journal_no_entry_date": "لا يوجد إدخال في هذا التاريخ",
"daily_journal_prompt_today": "أجب عن أسئلة اليوم لملء المفكرة.",
"daily_journal_prompt_other": "استخدم الأسهم لعرض الأيام الأخرى.",
"daily_journal_record_today": "سجّل اليوم",
"daily_journal_sleep_hours_label": "ساعات النوم",
"daily_journal_sleep_hours_hint": "مثال: ٧٫٥",
"daily_journal_sleep_quality_label": "جودة النوم (1–5)",
"daily_journal_caffeine_label": "الكافيين بالأمس",
"daily_journal_caffeine_cups": "أكواب",
"daily_journal_alcohol_label": "الكحول بالأمس",
"daily_journal_alcohol_drinks": "مشروبات",
"daily_journal_hydration_label": "ترطيب (لترات)",
"daily_journal_hydration_hint": "مثال: ٢٫٥",
"daily_journal_soreness_label": "شعرت بألم أو إرهاق",
"daily_journal_stress_label": "مستوى التوتر (1–5)",
"daily_journal_mood_label": "المزاج عند الاستيقاظ (1–5)",
"daily_journal_sexual_activity_label": "نشاط جنسي",
"daily_journal_screen_time_label": "وقت الشاشة قبل النوم",
"daily_journal_productivity_label": "الإنتاجية والتركيز أثناء اليوم (1–5)",
"daily_journal_motivation_label": "الدافع للتدريب (1–5)",
"daily_journal_supplements_label": "تناولت مكملات أو أدوية",
"daily_journal_copy_last": "مثل المرة السابقة",
"daily_journal_save_entry": "حفظ الإدخال",
"daily_journal_section_sleep": "النوم والتعافي",
"daily_journal_section_hydration": "الترطيب والاستهلاك",
"daily_journal_section_focus": "التركيز والتدريب",
"daily_journal_sleep_hours_row": "ساعات النوم",
"daily_journal_hours_suffix": "س",
"daily_journal_sleep_quality_row": "جودة النوم",
"daily_journal_mood_row": "المزاج عند الاستيقاظ",
"daily_journal_soreness_row": "ألم أو إرهاق",
"daily_journal_hydration_row": "الترطيب",
"daily_journal_caffeine_row": "الكافيين",
"daily_journal_alcohol_row": "الكحول",
"daily_journal_supplements_row": "مكملات/أدوية",
"daily_journal_productivity_row": "الإنتاجية/التركيز",
"daily_journal_motivation_row": "الدافع للتدريب",
"daily_journal_sexual_row": "نشاط جنسي",
"daily_journal_screen_row": "وقت الشاشة قبل النوم",
"daily_journal_entry_for": "إدخال بتاريخ",
"daily_journal_no_entry_for": "لا يوجد إدخال بتاريخ",
"daily_journal_yes": "نعم",
"daily_journal_no": "لا",
"daily_journal_cup_single": "كوب",
"daily_journal_cup_plural": "أكواب",
"daily_journal_drink_single": "مشروب",
"daily_journal_drink_plural": "مشروبات",
"daily_journal_sign_in_submit": "يرجى تسجيل الدخول لإرسال المفكرة.",
"daily_journal_saved": "تم حفظ المفكرة اليومية.",
"daily_journal_already_submitted": "تم الإرسال اليوم بالفعل.",
"daily_journal_failed_save": "فشل الحفظ: {error}",
"daily_journal_no_previous": "لا يوجد إدخال سابق للنسخ.",
"daily_journal_copied": "تم نسخ آخر إدخال لليوم.",
"daily_journal_failed_copy": "فشل النسخ: {error}",
"announcements_title": "الإعلانات",
"latest_news": "آخر الأخبار",
"no_announcements": "لا توجد إعلانات بعد.",
"steps_title": "الخطوات",
"steps_edit_today": "تعديل خطوات اليوم",
"steps_goal_btn": "الهدف: {value}",
"sleep_title": "النوم",
"sleep_edit_today": "تعديل نوم اليوم",
"sleep_goal_btn": "الهدف: {value} س",
"calories_title": "السعرات المحروقة",
"calories_edit_today": "تعديل سعرات اليوم",
"calories_goal_btn": "الهدف: {value} سعرة",
"range_weekly": "أسبوعي",
"range_monthly": "شهري",
"range_yearly": "سنوي",
"last_7_days": "آخر 7 أيام",
"range_last7": "آخر 7 أيام",
"range_last30": "آخر 30 يوماً",
"range_last_year": "آخر سنة",
"no_steps_range": "لا توجد بيانات خطوات لهذه المدة.",
"no_sleep_range": "لا توجد بيانات نوم لهذه المدة.",
"no_calories_range": "لا توجد بيانات سعرات لهذه المدة.",
"profile_update_success": "تم تحديث الملف الشخصي",
"profile_update_failed": "فشل تحديث الملف الشخصي",
"no_changes": "لا توجد تغييرات للحفظ",
"invalid_number": "أدخل رقماً صحيحاً",
      "university_student_question": "هل أنت طالب جامعي حالياً؟",
      "physical_rehab_question": "هل تستخدم تطبيق طاقة لإعادة التأهيل الجسدي أو العلاج الفيزيائي؟",
"select_university": "اختر الجامعة",
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(LocalizationsDelegate old) => false;
}
