import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_tagline': 'Log your workouts easily, all in one place.',
      'saved_accounts': 'Saved accounts',
      'login': 'Log in',
      'login_with_another': 'Log in using another account',
      'login_as': 'Log in as',
      'new_to_taqa': 'New to TAQA? ',
      'signup': 'Sign up',

      'verification_title': 'Verify Email',
      'verification_sent': 'A verification code has been sent to:',
      'enter_code': 'Enter verification code',
      'hint_code': '6-digit code',
      'verify_btn': 'Verify',
      'resend_btn': 'Resend code',
      'resend_wait': 'Resend available in {seconds} sec',
      'code_invalid': 'Code must be 6 digits',
      'verified_success': 'Email verified successfully!',
      'verified_failed': 'Verification failed',
      'resend_failed': 'Resend failed',
      'resend_success': 'New verification code sent',

      "login_title": "Login",
      "email": "Email",
      "password": "Password",
      "email_hint": "example@gmail.com",
      "password_hint": "Your password",
      "forgot_password": "Forgot Password?",
      "login_btn": "Login",
      "or": "or",
      "apple_login": "Sign in with Apple",
      "google_login": "Sign in with Google",
      "error_required_fields": "Email and password are required",
      "network_error": "Network error",
      "welcome_user": "Welcome, {name}",
      "account_no_longer_exists": "Account no longer exists.",

      "signup_title": "Create Account",
      "signup_username": "Username",
      "signup_username_hint": "yourname_123",
      "signup_fullname": "Full Name",
      "signup_fullname_hint": "First Last",
      "signup_btn": "Create Account",
      "signup_required_fields": "All fields are required.",
      "signup_username_short": "Username must be at least 3 characters.",
      "signup_username_long": "Username cannot exceed 50 characters.",
      "signup_username_invalid": "Username can use letters, numbers, '.', '-' or '_'.",
      "signup_email_invalid": "Enter a valid email.",
      "signup_password_short": "Password must be at least 8 characters.",
      "signup_failed": "Signup failed.",
      "google_signup": "Continue with Google",
      "google_success_message": "Signed in with Google. Welcome back!",
      "signup_expert_title": "Create Expert Account",
      "signup_expert_btn": "Create Expert Account",
      "signup_as_expert": "Sign up as expert",
      "signup_expert_note": "Experts manage the platform. Expert accounts may require approval.",

      "questionnaire_title": "Personalized Form",
      "questionnaire_intro_title": "Let’s personalize your plan",
      "questionnaire_intro_text":
          "Answer a few questions so we can adapt your workouts and nutrition to your body, lifestyle, and goals.",
      "questionnaire_chip_time": "Takes ~3–5 min",
      "questionnaire_chip_personal": "Fully personalized",
      "questionnaire_chip_private": "Your data is private",

      "expert_questionnaire_title": "Expert Questionnaire",
      "expert_questionnaire_intro_title": "Tell us about your expertise",
      "expert_questionnaire_intro_text": "A focused 27-question form to understand your background, specialties, and how you can support clients.",
      "expert_questionnaire_chip_count": "27 questions",
      "expert_questionnaire_chip_time": "Takes ~5–8 min",
      "expert_questionnaire_chip_quality": "Helps vet expertise",
      "expert_questionnaire_submit": "Submit expert questionnaire",
      "expert_question_label": "Question",
      "expert_question_hint": "Type your response",
      "expert_section_experience": "Experience",
      "expert_section_experience_sub": "Years coaching, background, education.",
      "expert_section_specialty": "Specialties",
      "expert_section_specialty_sub": "Training styles, nutrition focus, tools.",
      "expert_section_clients": "Clients & availability",
      "expert_section_clients_sub": "Who you serve, capacity, time zones.",
      "expert_placeholder_title": "Expert questionnaire",
      "expert_placeholder_desc": "We’re preparing a tailored 27-question flow. For now, submit to continue.",
      "expert_placeholder_block_title": "Coming soon",
      "expert_placeholder_block_desc": "Detailed expertise questions will appear here.",
      "expert_submission_title": "Application submitted",
      "expert_submission_headline": "Thank you for your expertise",
      "expert_submission_body": "Your expert application was submitted successfully. Please allow 24–48 hours while we review your details.",
      "expert_submission_next_steps": "What happens next",
      "expert_submission_step_review": "We’ll review your answers and verify your expertise.",
      "expert_submission_step_notify": "You’ll receive an email once your application is approved.",
      "expert_submission_step_dashboard": "If approved, you’ll see your expert dashboard unlocked.",
      "expert_questionnaire_already_done": "You already submitted the expert questionnaire.",

      "section_basics_title": "Basics",
      "section_basics_sub": "Age, height, weight, body type.",
      "section_goals_title": "Goals",
      "section_goals_sub": "What you want to achieve & by when.",
      "section_training_title": "Training",
      "section_training_sub": "Experience, days per week, style.",
      "section_nutrition_title": "Nutrition",
      "section_nutrition_sub": "Diet type, allergies, meals.",
      "section_lifestyle_title": "Lifestyle & Health",
      "section_lifestyle_sub": "Sleep, stress, any conditions.",

      "start_questionnaire": "Start questionnaire",
      "update_later": "You can always update your answers later.",
      "save_success": "Questionnaire saved successfully",
      "save_error": "Error saving questionnaire",
      "user_missing": "User ID missing – login again",
      "not_set": "Not set",
      "set_button": "Set",
      "yes": "Yes",
      "no": "No",
      "affiliation": "Affiliation",

      "sec_basic_title": "Basic Info",
      "sec_goals_title": "Goals & Motivation",
      "sec_training_title": "Training",
      "sec_nutrition_title": "Nutrition",
      "sec_lifestyle_title": "Lifestyle & Recovery",
      "sec_affiliation_title": "Affiliation",
      "sec_affiliation_sub": "Confirm your gym/hospital or add your own.",
      "sec_health_title": "Health & Settings",

      "sec_basic_sub": "Tell us your basic body information.",
      "sec_goals_sub": "What you want to achieve and why.",
      "sec_training_sub": "How you like to train and what you can do.",
      "sec_nutrition_sub": "Your diet habits and preferences.",
      "sec_lifestyle_sub": "Your daily routine, sleep and stress.",
      "sec_health_sub": "Health details and how flexible your plan is.",

      "step": "Step",
      "of": "of",
      "back": "Back",
      "next": "Next",
      "finish": "Finish",

      "sex": "Sex",
      "male": "Male",
      "female": "Female",
      "prefer_not": "Prefer not to say",

      "age": "Age",
      "height": "Height",
      "weight": "Weight",

      "goal_main": "What is your main goal?",
      "lose_weight": "Lose weight",
      "gain_muscle": "Gain muscle",
      "improve_endurance": "Improve endurance",
      "maintain_fitness": "Maintain fitness",
      "improve_health": "Improve health",

      "motivation": "What motivates you most?",
      "look_better": "Look better",
      "feel_stronger": "Feel stronger",
      "health_better": "Improve health",
      "more_energy": "Increase energy",
      "mental_wellbeing": "Mental well-being",

      "important_muscles": "Which muscles are most important to you?",
      "arms": "Arms",
      "shoulders": "Shoulders",
      "abs": "Abs",
      "legs": "Legs",
      "all_body": "All body",

      "time_change": "How soon do you want to see change?",
      "no_timeframe": "No timeframe",

      "deadline": "Do you have a deadline?",
      "sport": "Sporting event",
      "wedding": "Wedding",
      "birthday": "Birthday",
      "vacation": "Vacation",
      "other": "Other",

      "body_type": "Current body type",
      "slender": "Slender",
      "average": "Average",
      "muscular": "Muscular",
      "heavy": "Heavy",

      "fitness_experience": "Fitness experience",
      "beginner": "Beginner (<6 months)",
      "intermediate": "Intermediate (6–24 months)",
      "advanced": "Advanced (>2 years)",

      "training_days": "Training days per week",
      "preferred_time": "Preferred time",
      "morning": "Morning",
      "noon": "Noon",
      "afternoon": "Afternoon",
      "evening": "Evening",
      "flexible": "Flexible",

      "training_location": "Where do you train?",
      "gym": "Gym",
      "home": "Home",
      "hybrid": "Hybrid",

      "equipment": "Equipment access",
      "dumbbells": "Dumbbells",
      "barbell": "Barbell",
      "resistance_bands": "Resistance bands",
      "bodyweight": "Bodyweight only",
      "machines": "Machines",
      "mix": "Mix",

      "training_style": "Preferred training style",
      "strength": "Strength",
      "hypertrophy": "Hypertrophy",
      "functional": "Functional",
      "endurance": "Endurance",
      "hiit": "HIIT",
      "mobility": "Mobility",

      "past_injuries": "Past injuries",
      "shoulder": "Shoulder",
      "knee": "Knee",
      "elbow": "Elbow",
      "none": "None",

      "train_mode": "Train mode",
      "alone": "Alone",
      "partner": "With partner",
      "trainer": "With trainer",

      "auto_recovery": "Include recovery?",

      "diet_type": "Preferred diet",
      "no_pref": "No preference",
      "high_protein": "High protein",
      "low_carb": "Low carb",
      "vegetarian": "Vegetarian",
      "vegan": "Vegan",
      "fasting": "Intermittent fasting",

      "allergies": "Allergies",
      "dairy": "Dairy",
      "gluten": "Gluten",
      "nuts": "Nuts",
      "shellfish": "Shellfish",

      "meals_per_day": "Meals per day",
      "food_habit": "Food habit",
      "cook": "Mostly cook",
      "eat_out": "Mostly eat out",

      "kitchen_access": "Kitchen access",

      "supplements": "Supplements",
      "protein": "Protein",
      "creatine": "Creatine",
      "multivitamin": "Multivitamin",

      "water_intake": "Daily water intake",
      "meal_plan": "Meal plan type",
      "low_budget": "Low budget",
      "moderate": "Moderate",

      "daily_activity": "Daily activity level",
      "sedentary": "Sedentary (desk job)",
      "active": "Active",
      "highly_active": "Highly physical",

      "sleep_hours": "Sleep duration",
      "sleep_consistency": "Sleep consistency",
      "regular": "Regular",
      "irregular": "Irregular",

      "wake_feeling": "Wake feeling",
      "tired": "Tired",
      "okay": "Okay",
      "refreshed": "Refreshed",

      "stress_level": "Stress level",
      "affiliation_heading": "Affiliation",
      "affiliation_category": "Affiliation category",
      "affiliation_select": "Select your institution",
      "affiliation_loading": "Loading affiliations...",
      "affiliation_other": "Other affiliation",
      "affiliation_other_hint": "Type the gym, clinic, or organization name",
      "affiliation_help": "Choose from the list or type it if you don't see it.",
      "affiliation_required": "Please pick an affiliation or type one.",
      "affiliation_none_value": "Not affiliated",
      "affiliation_prompt": "Are you affiliated with a gym/hospital?",
      "affiliation_load_error": "Could not load affiliations. You can still type your own.",

      "chronic_conditions": "Chronic conditions",
      "chronic_prompt": "Do you have chronic diseases?",
      "chronic_none_value": "None",
      "auto_adjust": "Auto-adjust weekly?",
      "consent_tracking": "Consent to tracking?",
      "consent_required": "You must allow tracking to continue.",

      "required": "This field is required",
      "select_option": "Please select an option",
      "select_one": "Please select at least one option",
      "send_reset_code": "Send Reset Code",
"verify_reset_code": "Verify Reset Code",
"reset_code_sent_to": "A reset code was sent to:",
"reset_code_resent": "Reset code resent.",
"enter_reset_code": "Enter the reset code.",
"reset_password": "Reset Password",
"new_password": "New Password",
"retype_password": "Retype Password",
"fill_all_fields": "Please fill all fields.",
"passwords_do_not_match": "Passwords do not match.",
"reset_failed": "Password reset failed.",
"password_reset_success": "Password changed successfully!",
"profile_title": "Profile",
"edit_profile": "Edit Profile",
"sign_out": "Sign Out",
"profile_goals_title": "Goals",
"profile_main_goal": "Main Goal",
"profile_workout_freq": "Workout Frequency",
"profile_diet_pref": "Diet Preference",

"profile_info_title": "Personal Information",
"profile_age": "Age",
"profile_sex": "Sex",
"profile_height": "Height",
"profile_weight": "Weight",
"profile_user_name": "User Name",
"profile_occupation": "Occupation",
"profile_experience": "Experience",
"profile_days_per_week": "days/week",
"settings": "Settings",
"coming_soon": "Coming soon",
"settings_language": "Language",
"settings_change_password": "Change password",
"settings_change_password_sub": "Reset your password via email",
"settings_security": "Security",
"settings_profile": "Profile",
"settings_change_username": "Change username",
"settings_change_username_sub": "Update your public username",
"username_updated": "Username updated",
"ok": "OK",
"settings_change_avatar": "Change avatar",
"settings_change_avatar_sub": "Pick a new profile picture",
"permissions_required": "Camera or photo access is required to change your avatar.",
"avatar_updated": "Avatar updated",
"settings_be_expert": "Be an expert",
"settings_be_expert_sub": "Start the expert questionnaire",
"settings_support": "Support",
"settings_contact": "Contact us",
"settings_contact_sub": "Reach our support team",
"settings_contact_body": "Email us at support@taqa.app and we'll get back to you shortly.",
"settings_help": "Help & FAQ",
"settings_help_sub": "Common questions and answers",
"settings_help_body": "We’re preparing a help center. In the meantime, contact support for any issue.",
"dash_stay_tuned": "Stay tuned",
"dash_announce_here": "Announcements will appear here.",
"dash_news_tag": "News",
"dash_welcome_back": "Welcome back",
"dash_dashboard": "Dashboard",
"dash_hi_name": "Hi, {name}",
"dash_today_steps": "Today's steps",
"dash_today_sleep": "Today's sleep",
"dash_water_intake": "Water intake",
"dash_calories_burned": "Calories burned",
"dash_goal": "Goal",
"dash_unit_l": "L",
"dash_unit_hrs": "hrs",
"dash_unit_kcal": "kcal",
"dash_loading": "Loading…",
"dash_target": "Target",
"dash_steps_week": "steps / week",
"dash_steps_label": "steps",
"water_title": "Water intake",
"water_goal_label": "Daily goal (L)",
"water_goal_hint": "e.g. 2.5",
"water_intake_label": "Today's intake (L)",
"water_intake_hint": "e.g. 1.8",
"common_cancel": "Cancel",
"common_save": "Save",
"dash_weekly_goal": "Weekly movement goal",
"dash_7day_trends": "7-day trends",
"dash_sleep_hrs": "Sleep (hrs)",
"dash_calories_scaled": "Calories (x100 kcal)",
"dash_no_sleep_data": "No sleep data",
"dash_no_calories_data": "No calories data",
"dash_fueling": "Fueling compliance",
"dash_muscle": "Muscle stimulus",
"dash_taqa_score": "Taqa Score",
"dash_placeholder": "Placeholder",
"journal_title": "Daily Journal",
"journal_placeholder": "Journal placeholder",
"journal_hint": "Tap notifications to land here.",
"announcements_title": "Announcements",
"latest_news": "Latest news",
"no_announcements": "No announcements yet.",
"steps_title": "Steps",
"steps_edit_today": "Edit today's steps",
"steps_goal_btn": "Goal: {value}",
"sleep_title": "Sleep",
"sleep_edit_today": "Edit today's sleep",
"sleep_goal_btn": "Goal: {value} h",
"calories_title": "Calories burned",
"calories_edit_today": "Edit today's calories",
"calories_goal_btn": "Goal: {value} kcal",
"range_weekly": "Weekly",
"range_monthly": "Monthly",
"range_yearly": "Yearly",
"last_7_days": "Last 7 days",
"range_last7": "Last 7 days",
"range_last30": "Last 30 days",
"range_last_year": "Last year",
"no_steps_range": "No steps data for this range.",
"no_sleep_range": "No sleep data for this range.",
"no_calories_range": "No calorie data for this range.",
"profile_update_success": "Profile updated",
"profile_update_failed": "Profile update failed",
"no_changes": "No changes to save",
"invalid_number": "Enter a valid number",
      "university_student_question": "Are you currently a university student?",
          "select_university": "Select your university",
          "physical_rehab_question": "Are you using TAQA for physical rehabilitation or physiotherapy?",
    },

    'ar': {
      'welcome_tagline': 'سجّل تمارينك بسهولة، في مكان واحد.',
      'saved_accounts': 'الحسابات المحفوظة',
      'login': 'تسجيل الدخول',
      'login_with_another': 'تسجيل الدخول باستخدام حساب آخر',
      'login_as': 'تسجيل الدخول باسم',
      'new_to_taqa': 'هل أنت جديد في TAQA؟ ',
      'signup': 'إنشاء حساب',

      'verification_title': 'تأكيد البريد الإلكتروني',
      'verification_sent': 'تم إرسال رمز التحقق إلى:',
      'enter_code': 'أدخل رمز التحقق',
      'hint_code': 'رمز مكوّن من 6 أرقام',
      'verify_btn': 'تأكيد',
      'resend_btn': 'إعادة إرسال الرمز',
      'resend_wait': 'يمكن إعادة الإرسال خلال {seconds} ثانية',
      'code_invalid': 'الرمز يجب أن يكون 6 أرقام',
      'verified_success': 'تم تأكيد البريد بنجاح!',
      'verified_failed': 'فشل التحقق',
      'resend_failed': 'فشل الإرسال',
      'resend_success': 'تم إرسال رمز جديد',

      "login_title": "تسجيل الدخول",
      "email": "البريد الإلكتروني",
      "password": "كلمة المرور",
      "email_hint": "example@gmail.com",
      "password_hint": "كلمة المرور الخاصة بك",
      "forgot_password": "هل نسيت كلمة المرور؟",
      "login_btn": "تسجيل الدخول",
      "or": "أو",
      "apple_login": "تسجيل الدخول عبر Apple",
      "google_login": "تسجيل الدخول عبر Google",
      "error_required_fields": "البريد الإلكتروني وكلمة المرور مطلوبان",
      "network_error": "خطأ في الشبكة",
      "welcome_user": "مرحباً، {name}",
      "account_no_longer_exists": "الحساب غير موجود.",

      "signup_title": "إنشاء حساب",
      "signup_username": "اسم المستخدم",
      "signup_username_hint": "yourname_123",
      "signup_fullname": "الاسم الكامل",
      "signup_fullname_hint": "الاسم الأول والاسم الأخير",
      "signup_btn": "إنشاء حساب",
      "signup_required_fields": "جميع الحقول مطلوبة.",
      "signup_username_short": "يجب أن يكون اسم المستخدم 3 أحرف على الأقل.",
      "signup_username_long": "لا يمكن أن يتجاوز اسم المستخدم 50 حرفًا.",
      "signup_username_invalid": "يمكن استخدام الحروف والأرقام و '.' و '-' و '_'.",
      "signup_email_invalid": "أدخل بريدًا إلكترونيًا صالحًا.",
      "signup_password_short": "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
      "signup_failed": "فشل في إنشاء الحساب.",
      "google_signup": "المتابعة عبر Google",
      "google_success_message": "تم تسجيل الدخول عبر Google. أهلاً بعودتك!",
      "signup_expert_title": "إنشاء حساب خبير",
      "signup_expert_btn": "إنشاء حساب خبير",
      "signup_as_expert": "التسجيل كخبير",
      "signup_expert_note": "هذا الخيار مخصص لخبراء المنصة. قد يتطلب الحساب موافقة قبل التفعيل.",

      "questionnaire_title": "النموذج الشخصي",
      "questionnaire_intro_title": "لنخصّص خطتك",
      "questionnaire_intro_text":
          "أجب عن بعض الأسئلة لنكي نكيّف التمارين والتغذية حسب جسمك وأسلوب حياتك وأهدافك.",
      "questionnaire_chip_time": "يستغرق ~3–5 دقائق",
      "questionnaire_chip_personal": "مخصّص بالكامل",
      "questionnaire_chip_private": "بياناتك خاصة",

      "expert_questionnaire_title": "نموذج الخبير",
      "expert_questionnaire_intro_title": "حدثنا عن خبرتك",
      "expert_questionnaire_intro_text": "نموذج من 27 سؤالاً لفهم خبرتك، تخصصاتك، وكيفية دعمك للعملاء.",
      "expert_questionnaire_chip_count": "27 سؤالاً",
      "expert_questionnaire_chip_time": "يستغرق ~5–8 دقائق",
      "expert_questionnaire_chip_quality": "يساعدنا على تقييم الخبرة",
      "expert_questionnaire_submit": "إرسال نموذج الخبير",
      "expert_question_label": "السؤال",
      "expert_question_hint": "اكتب إجابتك",
      "expert_section_experience": "الخبرة",
      "expert_section_experience_sub": "سنوات التدريب، الخلفية، التعليم.",
      "expert_section_specialty": "التخصصات",
      "expert_section_specialty_sub": "أنماط التدريب، التركيز الغذائي، الأدوات.",
      "expert_section_clients": "العملاء والتوفر",
      "expert_section_clients_sub": "من تخدم، الطاقة الاستيعابية، المناطق الزمنية.",
      "expert_placeholder_title": "نموذج الخبير",
      "expert_placeholder_desc": "نعمل على تدفق من 27 سؤالاً مخصصاً. يمكنك الإرسال الآن للمتابعة.",
      "expert_placeholder_block_title": "قريباً",
      "expert_placeholder_block_desc": "ستظهر هنا أسئلة تفصيلية عن خبرتك.",
      "expert_submission_title": "تم إرسال طلبك",
      "expert_submission_headline": "شكراً لمشاركتك خبرتك",
      "expert_submission_body": "تم إرسال طلبك كخبير بنجاح. يرجى السماح بـ 24–48 ساعة لمراجعة بياناتك.",
      "expert_submission_next_steps": "ما الذي سيحدث بعد ذلك",
      "expert_submission_step_review": "سنراجع إجاباتك ونُقيّم خبرتك.",
      "expert_submission_step_notify": "ستصلك رسالة بريد إلكتروني عند الموافقة على طلبك.",
      "expert_submission_step_dashboard": "عند الموافقة، ستجد لوحة تحكم الخبير متاحة لك.",
      "expert_questionnaire_already_done": "لقد أكملت استبيان الخبير بالفعل.",

      "section_basics_title": "الأساسيات",
      "section_basics_sub": "العمر، الطول، الوزن، نوع الجسم.",
      "section_goals_title": "الأهداف",
      "section_goals_sub": "ما تريد تحقيقه وبأي وقت.",
      "section_training_title": "التمارين",
      "section_training_sub": "الخبرة، أيام التدريب، الأسلوب.",
      "section_nutrition_title": "التغذية",
      "section_nutrition_sub": "نوع النظام الغذائي، الحساسية، عدد الوجبات.",
      "section_lifestyle_title": "نمط الحياة والصحة",
      "section_lifestyle_sub": "النوم، الضغط، أي حالات صحية.",

      "start_questionnaire": "ابدأ الاستبيان",
      "update_later": "يمكنك تعديل إجاباتك لاحقًا.",
      "save_success": "تم حفظ الاستبيان بنجاح",
      "save_error": "حدث خطأ أثناء الحفظ",
      "user_missing": "لا يوجد رقم مستخدم – يرجى تسجيل الدخول مجددًا",
      "not_set": "غير محدد",
      "set_button": "تعيين",
      "yes": "نعم",
      "no": "لا",
      "affiliation": "الانتساب",

      "sec_basic_title": "المعلومات الأساسية",
      "sec_goals_title": "الأهداف والدوافع",
      "sec_training_title": "التمارين",
      "sec_nutrition_title": "التغذية",
      "sec_lifestyle_title": "نمط الحياة والاستشفاء",
      "sec_affiliation_title": "جهة الانتساب",
      "sec_affiliation_sub": "أكد جهة الانتساب أو اكتبها إذا لم تجدها.",
      "sec_health_title": "الصحة والإعدادات",

      "sec_basic_sub": "أدخل معلوماتك الجسدية الأساسية.",
      "sec_goals_sub": "ما الذي تريد تحقيقه ولماذا.",
      "sec_training_sub": "أسلوب تدريبك وقدراتك.",
      "sec_nutrition_sub": "عاداتك الغذائية وتفضيلاتك.",
      "sec_lifestyle_sub": "روتينك اليومي، النوم والضغط.",
      "sec_health_sub": "تفاصيل صحية ومدى مرونة برنامجك.",

      "step": "الخطوة",
      "of": "من",
      "back": "رجوع",
      "next": "التالي",
      "finish": "إنهاء",

      "sex": "الجنس",
      "male": "ذكر",
      "female": "أنثى",
      "prefer_not": "أفضل عدم القول",

      "age": "العمر",
      "height": "الطول",
      "weight": "الوزن",

      "goal_main": "ما هو هدفك الأساسي؟",
      "lose_weight": "خسارة الوزن",
      "gain_muscle": "زيادة العضلات",
      "improve_endurance": "تحسين التحمل",
      "maintain_fitness": "الحفاظ على اللياقة",
      "improve_health": "تحسين الصحة",

      "motivation": "ما الذي يحفّزك أكثر؟",
      "look_better": "المظهر الأفضل",
      "feel_stronger": "الشعور بالقوة",
      "health_better": "تحسين الصحة",
      "more_energy": "طاقة أكبر",
      "mental_wellbeing": "الصحة النفسية",

      "important_muscles": "أي العضلات أهم بالنسبة لك؟",
      "arms": "الذراعين",
      "shoulders": "الأكتاف",
      "abs": "البطن",
      "legs": "الساقين",
      "all_body": "كل الجسم",

      "time_change": "متى تريد رؤية التغيير؟",
      "no_timeframe": "بدون إطار زمني",

      "deadline": "هل لديك موعد نهائي؟",
      "sport": "حدث رياضي",
      "wedding": "زفاف",
      "birthday": "عيد ميلاد",
      "vacation": "إجازة",
      "other": "أخرى",

      "body_type": "نوع الجسم",
      "slender": "نحيف",
      "average": "متوسط",
      "muscular": "عضلي",
      "heavy": "ثقيل",

      "fitness_experience": "الخبرة الرياضية",
      "beginner": "مبتدئ (<6 أشهر)",
      "intermediate": "متوسط (6–24 شهرًا)",
      "advanced": "متقدم (>سنتين)",

      "training_days": "أيام التمرين أسبوعيًا",
      "preferred_time": "الوقت المفضل",
      "morning": "الصباح",
      "noon": "الظهيرة",
      "afternoon": "بعد الظهر",
      "evening": "المساء",
      "flexible": "مرن",

      "training_location": "مكان التدريب",
      "gym": "نادي رياضي",
      "home": "المنزل",
      "hybrid": "كلاهما",

      "equipment": "توفّر المعدات",
      "dumbbells": "دمبلز",
      "barbell": "بار",
      "resistance_bands": "مقاومات",
      "bodyweight": "وزن الجسم فقط",
      "machines": "آلات",
      "mix": "خليط",

      "training_style": "أسلوب التدريب",
      "strength": "قوة",
      "hypertrophy": "تضخيم",
      "functional": "وظيفي",
      "endurance": "تحمل",
      "hiit": "HIIT",
      "mobility": "مرونة",

      "past_injuries": "الإصابات السابقة",
      "shoulder": "الكتف",
      "knee": "الركبة",
      "elbow": "الكوع",
      "none": "لا يوجد",

      "train_mode": "طريقة التدريب",
      "alone": "بمفردي",
      "partner": "مع شريك",
      "trainer": "مع مدرب",

      "auto_recovery": "تضمين الاستشفاء؟",

      "diet_type": "النظام الغذائي",
      "no_pref": "بدون تفضيل",
      "high_protein": "عالي البروتين",
      "low_carb": "منخفض الكربوهيدرات",
      "vegetarian": "نباتي",
      "vegan": "نباتي صارم",
      "fasting": "صيام متقطع",

      "allergies": "الحساسية",
      "dairy": "منتجات الألبان",
      "gluten": "الجلوتين",
      "nuts": "المكسرات",
      "shellfish": "المأكولات البحرية",

      "meals_per_day": "عدد الوجبات يوميًا",
      "food_habit": "عادات الطعام",
      "cook": "أطبخ غالبًا",
      "eat_out": "آكل خارج المنزل غالبًا",

      "kitchen_access": "إمكانية استخدام المطبخ",

      "supplements": "المكملات الغذائية",
      "protein": "بروتين",
      "creatine": "كرياتين",
      "multivitamin": "فيتامينات متعددة",

      "water_intake": "كمية الماء اليومية",
      "meal_plan": "نوع خطة الوجبات",
      "low_budget": "ميزانية منخفضة",
      "moderate": "متوسطة",

      "daily_activity": "مستوى النشاط اليومي",
      "sedentary": "خامل (عمل مكتبي)",
      "active": "نشط",
      "highly_active": "نشط جدًا",

      "sleep_hours": "مدة النوم",
      "sleep_consistency": "انتظام النوم",
      "regular": "منتظم",
      "irregular": "غير منتظم",

      "wake_feeling": "الشعور عند الاستيقاظ",
      "tired": "متعب",
      "okay": "عادي",
      "refreshed": "منتعش",

      "stress_level": "مستوى التوتر",
      "affiliation_heading": "جهة الانتساب",
      "affiliation_category": "فئة الجهة",
      "affiliation_select": "اختر الجهة",
      "affiliation_loading": "جارٍ تحميل الجهات...",
      "affiliation_other": "جهة أخرى",
      "affiliation_other_hint": "اكتب اسم النادي أو العيادة أو الجهة",
      "affiliation_help": "اختر من القائمة أو اكتبها إذا لم تجدها.",
      "affiliation_required": "يرجى اختيار جهة أو كتابتها.",
      "affiliation_none_value": "بدون جهة",
      "affiliation_prompt": "هل أنت منتسب لنادٍ أو مستشفى؟",
      "affiliation_load_error": "تعذّر تحميل الجهات، يمكنك كتابة الجهة يدويًا.",

      "chronic_conditions": "الحالات المزمنة",
      "chronic_prompt": "هل لديك أمراض مزمنة؟",
      "chronic_none_value": "لا يوجد",
      "auto_adjust": "تعديل تلقائي أسبوعيًا؟",
      "consent_tracking": "السماح بالتتبع؟",
      "consent_required": "يجب السماح بالتتبع للمتابعة.",

      "required": "هذا الحقل مطلوب",
      "select_option": "الرجاء اختيار خيار",
      "select_one": "الرجاء اختيار خيار واحد على الأقل",
      "send_reset_code": "إرسال رمز الإستعادة",
      "verify_reset_code": "تأكيد رمز الاستعادة",
"reset_code_sent_to": "تم إرسال رمز الاستعادة إلى:",
"reset_code_resent": "تم إعادة إرسال رمز الاستعادة.",
"enter_reset_code": "أدخل رمز الاستعادة.",
"reset_password": "إعادة تعيين كلمة المرور",
"new_password": "كلمة المرور الجديدة",
"retype_password": "أعد إدخال كلمة المرور",
"fill_all_fields": "يرجى تعبئة جميع الحقول.",
"passwords_do_not_match": "كلمتا المرور غير متطابقتين.",
"reset_failed": "فشل في إعادة تعيين كلمة المرور.",
"password_reset_success": "تم تغيير كلمة المرور بنجاح!",
"profile_title": "الملف الشخصي",
"edit_profile": "تعديل الملف",
"sign_out": "تسجيل الخروج",
"profile_goals_title": "الأهداف",
"profile_main_goal": "الهدف الرئيسي",
"profile_workout_freq": "معدل التمرين الأسبوعي",
"profile_diet_pref": "النظام الغذائي",
"profile_info_title": "المعلومات الشخصية",
"profile_age": "العمر",
"profile_sex": "الجنس",
"profile_height": "الطول",
"profile_weight": "الوزن",
"profile_occupation": "الوظيفة",
"profile_user_name": "اسم المستخدم",
"profile_experience": "الخبرة",
"profile_days_per_week": "أيام/أسبوع",
"settings": "الإعدادات",
"coming_soon": "قريباً",
"settings_language": "اللغة",
"settings_change_password": "تغيير كلمة المرور",
"settings_change_password_sub": "أعد تعيين كلمة المرور عبر البريد الإلكتروني",
"settings_security": "الأمان",
"settings_profile": "الملف الشخصي",
"settings_change_username": "تغيير اسم المستخدم",
"settings_change_username_sub": "تحديث اسمك العام",
"username_updated": "تم تحديث اسم المستخدم",
"ok": "حسناً",
"settings_change_avatar": "تغيير الصورة الشخصية",
"settings_change_avatar_sub": "اختر صورة جديدة للملف الشخصي",
"permissions_required": "مطلوب إذن الكاميرا أو الصور لتغيير صورتك الشخصية.",
"avatar_updated": "تم تحديث الصورة الشخصية",
"settings_be_expert": "كن خبيراً",
"settings_be_expert_sub": "ابدأ استبيان الخبير",
"settings_support": "الدعم",
"settings_contact": "اتصل بنا",
"settings_contact_sub": "تواصل مع فريق الدعم",
"settings_contact_body": "راسلنا على support@taqa.app وسنعاود الاتصال بك في أقرب وقت.",
"settings_help": "المساعدة والأسئلة الشائعة",
"settings_help_sub": "أبرز الأسئلة والإجابات",
"settings_help_body": "نجهّز مركز مساعدة. يمكنك التواصل مع الدعم لأي استفسار.",
"dash_stay_tuned": "ابقَ على اطلاع",
"dash_announce_here": "ستظهر الإعلانات هنا.",
"dash_news_tag": "أخبار",
"dash_welcome_back": "مرحباً بعودتك",
"dash_dashboard": "لوحة التحكم",
"dash_hi_name": "مرحباً، {name}",
"dash_today_steps": "خطوات اليوم",
"dash_today_sleep": "نوم اليوم",
"dash_water_intake": "شرب الماء",
"dash_calories_burned": "السعرات المحروقة",
"dash_goal": "الهدف",
"dash_unit_l": "لتر",
"dash_unit_hrs": "س",
"dash_unit_kcal": "سعرة",
"dash_loading": "جارٍ التحميل…",
"dash_target": "الهدف",
"dash_steps_week": "خطوة / أسبوع",
"dash_steps_label": "خطوة",
"water_title": "شرب الماء",
"water_goal_label": "الهدف اليومي (لتر)",
"water_goal_hint": "مثال 2.5",
"water_intake_label": "كمية اليوم (لتر)",
"water_intake_hint": "مثال 1.8",
"common_cancel": "إلغاء",
"common_save": "حفظ",
"dash_weekly_goal": "هدف الحركة الأسبوعي",
"dash_7day_trends": "اتجاهات 7 أيام",
"dash_sleep_hrs": "النوم (س)",
"dash_calories_scaled": "السعرات (x100)",
"dash_no_sleep_data": "لا توجد بيانات نوم",
"dash_no_calories_data": "لا توجد بيانات سعرات",
"dash_fueling": "الالتزام بالتغذية",
"dash_muscle": "تحفيز العضلات",
"dash_taqa_score": "درجة طاقة",
"dash_placeholder": "قريباً",
"journal_title": "المفكرة اليومية",
"journal_placeholder": "صفحة المفكرة",
"journal_hint": "اضغط على الإشعارات للوصول هنا.",
"announcements_title": "الإعلانات",
"latest_news": "آخر الأخبار",
"no_announcements": "لا توجد إعلانات بعد.",
"steps_title": "الخطوات",
"steps_edit_today": "تعديل خطوات اليوم",
"steps_goal_btn": "الهدف: {value}",
"sleep_title": "النوم",
"sleep_edit_today": "تعديل نوم اليوم",
"sleep_goal_btn": "الهدف: {value} س",
"calories_title": "السعرات المحروقة",
"calories_edit_today": "تعديل سعرات اليوم",
"calories_goal_btn": "الهدف: {value} سعرة",
"range_weekly": "أسبوعي",
"range_monthly": "شهري",
"range_yearly": "سنوي",
"last_7_days": "آخر 7 أيام",
"range_last7": "آخر 7 أيام",
"range_last30": "آخر 30 يوماً",
"range_last_year": "آخر سنة",
"no_steps_range": "لا توجد بيانات خطوات لهذه المدة.",
"no_sleep_range": "لا توجد بيانات نوم لهذه المدة.",
"no_calories_range": "لا توجد بيانات سعرات لهذه المدة.",
"profile_update_success": "تم تحديث الملف الشخصي",
"profile_update_failed": "فشل تحديث الملف الشخصي",
"no_changes": "لا توجد تغييرات للحفظ",
"invalid_number": "أدخل رقماً صحيحاً",
      "university_student_question": "هل أنت طالب جامعي حالياً؟",
      "physical_rehab_question": "هل تستخدم تطبيق طاقة لإعادة التأهيل الجسدي أو العلاج الفيزيائي؟",
"select_university": "اختر الجامعة",
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(LocalizationsDelegate old) => false;
}
