// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQrHSJfVb-a7u5L0oFKXOr3FspsBX6l_M',
    appId: '1:280853704980:web:dfa3140ed7030bbe985201',
    messagingSenderId: '280853704980',
    projectId: 'fitnessproj-30252',
    authDomain: 'fitnessproj-30252.firebaseapp.com',
    storageBucket: 'fitnessproj-30252.firebasestorage.app',
    measurementId: 'G-XGM2XCYCXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8LYUpmtj3BhsNPqE0kU18EjnnJ5MUi8',
    appId: '1:280853704980:android:6b7c673073ae96a7985201',
    messagingSenderId: '280853704980',
    projectId: 'fitnessproj-30252',
    storageBucket: 'fitnessproj-30252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc3LAz2ccltb93zJb-UYWBXdyNJRi4xww',
    appId: '1:280853704980:ios:5d1a8639d4d289ec985201',
    messagingSenderId: '280853704980',
    projectId: 'fitnessproj-30252',
    storageBucket: 'fitnessproj-30252.firebasestorage.app',
    iosBundleId: 'com.example.taqaproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc3LAz2ccltb93zJb-UYWBXdyNJRi4xww',
    appId: '1:280853704980:ios:5d1a8639d4d289ec985201',
    messagingSenderId: '280853704980',
    projectId: 'fitnessproj-30252',
    storageBucket: 'fitnessproj-30252.firebasestorage.app',
    iosBundleId: 'com.example.taqaproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQrHSJfVb-a7u5L0oFKXOr3FspsBX6l_M',
    appId: '1:280853704980:web:00144511859ba4ed985201',
    messagingSenderId: '280853704980',
    projectId: 'fitnessproj-30252',
    authDomain: 'fitnessproj-30252.firebaseapp.com',
    storageBucket: 'fitnessproj-30252.firebasestorage.app',
    measurementId: 'G-W0B5QY3L73',
  );
}
